### ISSUE TITLE
DM Sans font italicizes all bold text

### ISSUE THREAD

**Issue by justintadlock** [WordPress/twentytwentythree#100]
When bolding text either through a `fontWeight` definition in `theme.json` or via the editor (`<strong>` wrapper), the included DM Sans font also applies an italic style to the text.  This is not an issue with other font-families registered in the theme.

![dm-sans-strong](https://user-images.githubusercontent.com/1816309/186216530-24b248f0-233b-4975-bd97-62261cac531a.jpg)

**Steps to reproduce:**

Seting the `fontFamily` for anything to `var( --wp--preset--font-family--dm-sans )`.  The following sets the body style to use it:

```json
{
	"styles": {
		"typography": {
			"fontFamily": "var( --wp--preset--font-family--dm-sans )",
		}
	}
}
```

Then, test by bolding some text in the editor.  Example block code:

```html
<!-- wp:paragraph -->
<p>No, Corin, being old, <strong>thou canst not guess</strong>, Though in thy youth thou wast as true a lover As ever sigh'd upon a midnight pillow. A miserable world! As I do live by food, I met a fool, Who laid him down and bask'd him in the sun, And rail'd on Lady Fortune in good terms, In good set terms- and yet a motley fool. </p>
<!-- /wp:paragraph -->
```

**Comment by mikachan** [comment]
Thanks! This should be fixed by: https://github.com/WordPress/twentytwentythree/pull/81

**Comment by bgardner** [comment]
Circling back to verify this has been fixed.
