### ISSUE TITLE
Consider removing featured image from single post template

### ISSUE THREAD

**Issue by justintadlock** [WordPress/twentytwentythree#101]
When a theme uses the featured image in its single post template, it runs the risk of creating the "duplicate featured image problem."  This happens when a user also adds the image to the post content itself as shown in the following screenshot:

![tt3-duplicate-featured](https://user-images.githubusercontent.com/1816309/186219145-ac108327-da6c-4682-abd2-1cd308074003.jpg)

For Twenty Twenty-Three, the image is just sitting above the post itself.  It's not doing anything special, such as serving as a header background.  Plus, there are not many options for customizing the Post Featured Image block via `theme.json` (and no options at all to style this based on context: archive vs. single).  Having no featured image on single post templates also better matches the post editor to what the user sees on the front end.

An alternative approach might be to add a "No Featured Image" template (though, I'd prefer to flip that around to have a selectable "Featured Image" template and no featured image to be the default).

**Comment by mikachan** [comment]
Thanks for this! These are really good points.

> An alternative approach might be to add a "No Featured Image" template (though, I'd prefer to flip that around to have a selectable "Featured Image" template and no featured image to be the default).

I like this idea - having the default template with no featured image, and adding an optional template that includes the featured image 👍

**Comment by bph** [comment]
I change my mind of this monthly, if not weekly. Offering an opinionated single post without feature image as default, and offer a template with feature image is a great way to solve this dilemma. Great idea!
