### ISSUE TITLE
Variation "Sherbet"

### ISSUE THREAD

**Issue by bgardner** [WordPress/twentytwentythree#104]
**Screenshot:**

![Sherbet](https://user-images.githubusercontent.com/486261/186249488-d2ecda60-23bd-49f9-8557-6597a6d157f4.png)

**Figma:**
https://www.figma.com/file/p4qBWBvxIEvT0bAHdCwf23/TT3-Variation-%22Sherbet%22?node-id=2%3A9

**Theme.json:**
[variation-sherbet.json](https://github.com/WordPress/twentytwentythree/files/9471273/variation-sherbet.json.zip)

**Comment by beafialho** [comment]
This style variation has been selected to be bundled with the Twenty Twenty-Three default theme! @critterverse and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes:

![Sherbet](https://user-images.githubusercontent.com/65220155/188936202-debd0e6c-98c1-4dbf-b899-349f443a2e47.png)

- Incorporate wide content width (and possibly larger type sizes on the post titles within the query)
- We loved the all caps typography in the header area and thought this could this be carried throughout the post titles, buttons, etc
- We’d love to use Inter for this variation, which is currently only being used on “Pitch”
- Incorporate a very opinionated duotone effect like the [Retroactive variation](https://github.com/WordPress/twentytwentythree/pull/40) by @scruffian

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!

**Comment by scruffian** [comment]
Could we also add the button and separator styles from Retroactive?

**Comment by beafialho** [comment]
> Could we also add the button and separator styles from Retroactive?

I think the buttons can work! I like the separator styles too but I don't think they'll fit with the bold type in this variation. There's quite a lot going on already and I'm afraid it'll be confusing especially in templates such as "Blog (Alternative)".

**Comment by mikachan** [comment]
Closed with https://github.com/WordPress/twentytwentythree/pull/174.
