### ISSUE TITLE
Home: adjust spacing below posts area

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#110]
I think there needs to be more spacing below the posts, this is what the query block look like with a background color:

![image](https://user-images.githubusercontent.com/7422055/186390277-4f3b3b09-b41f-4d2f-9454-a580dd07bd09.png)

**Comment by carolinan** [comment]
The new layout styles are overriding bottom margin added to the query in theme.json:
```
body .is-layout-constrained > * + * {
    margin-block-start: 1.5rem;
    margin-block-end: 0;
}

body .is-layout-constrained > * {
    margin-block-start: 0;
    margin-block-end: 0;
}
```

**Comment by mikachan** [comment]
There is more spacing added in this PR, which may address this issue: https://github.com/WordPress/twentytwentythree/pull/111

> The new layout styles are overriding bottom margin added to the query in theme.json:

I'm not seeing this locally, I can still see the query block margin coming through:

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/1645628/186455781-43c66ebd-511e-4584-b5b9-29f425f521f0.png">

I'm using the latest GB trunk and TT3 trunk.

**Comment by carolinan** [comment]
Yes, the spacing in the templates work, but spacing in theme.json is overridden.

**Comment by mikachan** [comment]
Is this still an issue in the theme? It looks like we're not currently setting any margin on the query block in theme.json, but I can see if I do set one that it's overwritten...

I managed to overwrite it via theme.json using the following:

```
"core/query": {
	"spacing": {
		"margin": {
			"bottom": "500px !important"
		}
	}
},
```

It's not great, but it's at least a workaround for now.

**Comment by mikachan** [comment]
Closing as the theme has been merged into the WordPress Core SVN repository and is no longer maintained on GitHub.
