### ISSUE TITLE
Variation "Benjamin"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#118]
![Screenshot 2022-08-26 at 11 32 05](https://user-images.githubusercontent.com/20610429/186874526-dcf70da2-4e1e-422f-9985-94e109de77e5.png)

Figma:
https://www.figma.com/file/IeSIFxrumx7fZvlf0Zedzo/TT3-Variation-%22Benjamin%22?node-id=2%3A9

**Comment by carolinan** [comment]
I'd love to know if you built this with theme.json yet -how did you add individual styles to the post template inner content?

**Comment by anarieldesign** [comment]
> I'd love to know if you built this with theme.json yet -how did you add individual styles to the post template inner content?

@carolinan I thought there is a way similar we can do this in style.css with wp-block-post? I still didn't recreate this one in theme.json as I thought we are able to style it, to take that whole part. If not maybe this can be added to the theme.json? I think this would be very useful

**Comment by carolinan** [comment]
It is not a block, so it does not work ( I mean, _right now_)

**Comment by anarieldesign** [comment]
> It is not a block, so it does not work ( I mean, _right now_)

Yes I know it's not a block but was thinking maybe there is a way we can do it or add the option if it'a possible. If not u can delete this one or I'll remove it 🤗

**Comment by carolinan** [comment]
I wonder if we could add it to "elements" along with the buttons, captions etc

**Comment by anarieldesign** [comment]
> It is not a block, so it does not work ( I mean, _right now_)

I'll try to see for the theme.json file if I can come up with something with this part if not we can just remove it 😉

**Comment by anarieldesign** [comment]
> I wonder if we could add it to "elements" along with the buttons, captions etc

That would be amazing. I'll try to see in the theme.json if there is any way around it. But maybe there is a way to add it to the theme.json file 😅

**Comment by carolinan** [comment]
I think it is mostly a question about if using _elements_ is the best solution. 🤔

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
