### ISSUE TITLE
Variation "Lime"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#119]
![Screenshot 2022-08-26 at 12 18 13](https://user-images.githubusercontent.com/20610429/186882985-71555b03-43da-4d4d-820e-f088312eb5fb.png)

Figma: https://www.figma.com/file/ccgY4noOTGad52bZMe6Nf3/TT3-Variation-%22Lime%22?node-id=2%3A9

**Comment by anarieldesign** [comment]
@mikachan But again not sure if we are able to style the post content in the theme.json file. This would be very useful to have :)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
