### ISSUE TITLE
Variation: "Java Plum"

### ISSUE THREAD

**Issue by amjadr360** [WordPress/twentytwentythree#127]
![image](https://user-images.githubusercontent.com/32260742/187007712-52a11fc2-6fa2-491c-b5f0-ef30e1b79b34.png)
![image](https://user-images.githubusercontent.com/32260742/187007725-65afc3eb-d7b7-4d94-a5ee-5e53db0090b6.png)
![image](https://user-images.githubusercontent.com/32260742/187007731-a639db1b-5070-43bc-80e9-719f3c7ac0ea.png)
![image](https://user-images.githubusercontent.com/32260742/187007734-55506059-bbf6-4dfc-b994-3b55534d99f2.png)

Figma: https://www.figma.com/file/VEVbYQ4xURN9Mjz55I4eTx/Variation-Java-Plum?node-id=0%3A1
Variation JSON: [java-plum.zip](https://github.com/WordPress/twentytwentythree/files/9437032/java-plum.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
