### ISSUE TITLE
Variation: "Orange"

### ISSUE THREAD

**Issue by amjadr360** [WordPress/twentytwentythree#128]
![image](https://user-images.githubusercontent.com/32260742/187008062-c55df1ae-1767-41a5-850b-1e6f4a134327.png)
![image](https://user-images.githubusercontent.com/32260742/187008066-29b6da3a-71f2-4e86-9b45-5a0a69493e28.png)
![image](https://user-images.githubusercontent.com/32260742/187008072-9318be9d-f710-439f-8c6e-2473b030ce9d.png)
![image](https://user-images.githubusercontent.com/32260742/187008077-9dae6d00-a21e-418d-9181-8fc08f0dff10.png)

Figma: https://www.figma.com/file/bpnVY7SdRW2uqxh9Vj5DaN/Variation-Orange?node-id=0%3A1
Variation JSON: [orange.zip](https://github.com/WordPress/twentytwentythree/files/9437038/orange.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
