### ISSUE TITLE
Variation: "Guava"

### ISSUE THREAD

**Issue by amjadr360** [WordPress/twentytwentythree#129]
![image](https://user-images.githubusercontent.com/32260742/187008131-a0063112-daea-4304-9834-aa403e89f72d.png)
![image](https://user-images.githubusercontent.com/32260742/187008134-f395c47e-022d-4461-8777-a360529e6f40.png)
![image](https://user-images.githubusercontent.com/32260742/187008136-c78a0c7d-dfb4-4b4d-9c71-4c67ada66881.png)
![image](https://user-images.githubusercontent.com/32260742/187008138-b1e42e31-87b5-4291-9c9b-6b7ac9dae000.png)

Figma: https://www.figma.com/file/CHYJjrGVT5hh9vTmE75nhs/Variation-Guava?node-id=0%3A1
Variation JSON: [guava.zip](https://github.com/WordPress/twentytwentythree/files/9437043/guava.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
