### ISSUE TITLE
Variation: "Snowberry"

### ISSUE THREAD

**Issue by amjadr360** [WordPress/twentytwentythree#130]
![image](https://user-images.githubusercontent.com/32260742/187008189-b59f261f-d6b3-457b-a407-866b5e4cc074.png)
![image](https://user-images.githubusercontent.com/32260742/187008206-4c317ea2-e733-4eaa-aa97-fba44be83896.png)
![image](https://user-images.githubusercontent.com/32260742/187008209-75d91125-6e8c-4326-b444-4362de15933b.png)
![image](https://user-images.githubusercontent.com/32260742/187008210-e09ca96c-5bd0-4d82-9258-d49158883f67.png)

Figma: https://www.figma.com/file/gZPJE13a3lwVLk3XOkABkh/Variation-Snowberry?node-id=1%3A22
Variation JSON: [snowberry.zip](https://github.com/WordPress/twentytwentythree/files/9437045/snowberry.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
