### ISSUE TITLE
Variation: Pilgrimage

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentythree#134]
<img width="495" alt="grafik" src="https://user-images.githubusercontent.com/7585600/187469919-f154581c-f84d-4d33-ae61-8ca9f7885d5f.png">

<img width="919" alt="grafik" src="https://user-images.githubusercontent.com/7585600/187470438-c1f25593-070d-4a42-968f-651daf8b5b2c.png">

<img width="992" alt="grafik" src="https://user-images.githubusercontent.com/7585600/187470169-3955a8dc-f138-4442-9aab-6a7a84c54cde.png">

Figma: https://www.figma.com/file/0NcNCYScCtXrgbUQ6Z6fAf/TT3%3A-Pilgrimage

**Comment by critterverse** [comment]
This style variation has been selected to be bundled with the Twenty Twenty-Three default theme! @beafialho and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes: 

![Pilgrimage](https://user-images.githubusercontent.com/77359364/188936250-e8d824f1-6750-45b3-a7c4-2f023e8edd23.png)

- Let’s try the bright green neon colors for some of the text such as post titles to make this variation even more vibrant
- Same note as above for separator lines
- Could we add a bright colored duotone effect to images if [overlay functionality](https://github.com/WordPress/gutenberg/issues/43676) doesn't ship in time for 6.1?
- We also thought this variation would be super cool with a subtle background gradient that incorporates a CSS pattern (like the one previously proposed in [Gutenberg issue #38577](https://github.com/WordPress/gutenberg/issues/38577)) to showcase how much the background can be customized.

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!

**Comment by kathryncodes** [comment]
Hi @mikachan, I'd love to take a stab at updating the theme.json files! This would be my first open source contribution, so I just wanted to know if there's anything specific I should know before jumping in?

**Comment by mikachan** [comment]
@kathryncodes, awesome! There's a [getting started guide in the readme](https://github.com/WordPress/twentytwentythree#getting-started) which should help you get your environment set up. Gutenberg also has a great guide for [working with Git](https://developer.wordpress.org/block-editor/contributors/code/git-workflow/), including forking a repository and creating a pull request.

Just let us know if you need any help!

**Comment by luminuu** [comment]
I just saw that the PR for adding gradients to the Post Featured Image block has been merged: https://github.com/WordPress/gutenberg/pull/43838

Can we explore adding my original idea of using gradients on the featured images, or do we have to stick to the proposed changes by @critterverse?

**Comment by critterverse** [comment]
>Can we explore adding my original idea of using gradients on the featured images, or do we have to stick to the proposed changes by @critterverse?

Definitely! Excited to see that one get merged 🎉

It would be great if we could keep some of the other edits that were suggested (type colors, separator color, and background pattern) but that sounds great to go with the overlay functionality instead of the duotone.
