### ISSUE TITLE
Variation: Summer Night

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentythree#135]
<img width="498" alt="grafik" src="https://user-images.githubusercontent.com/7585600/187470732-381ff897-a3af-43fa-8332-f1d25158944f.png">

<img width="896" alt="grafik" src="https://user-images.githubusercontent.com/7585600/187470866-2a283a76-8c82-4977-988d-2f1707e17a5b.png">

<img width="990" alt="grafik" src="https://user-images.githubusercontent.com/7585600/187471056-d4388172-128b-4ead-a640-5115da0e3dd8.png">

Figma: https://www.figma.com/file/zv2xtSrcjPQl1AtiVbdX2H/TT3%3A-Summer-Night?node-id=2%3A11

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
