### ISSUE TITLE
Variation "Marigold"

### ISSUE THREAD

**Issue by nudgeD** [WordPress/twentytwentythree#137]
<img width="250" alt="Variation-colors" src="https://user-images.githubusercontent.com/978114/187569515-22ba5088-5fdc-4515-b149-a7d279d74199.png">

![Homepage](https://user-images.githubusercontent.com/978114/187569535-9fd33a21-7bfd-41a3-9fdd-e9bc9913a009.png)

<img width="1326" alt="Colors" src="https://user-images.githubusercontent.com/978114/187569550-d7a2bc8f-8bab-4264-b687-e2aede11751b.png">

<img width="1431" alt="Buttons and Links" src="https://user-images.githubusercontent.com/978114/187569568-083e9337-ef40-4255-b225-c484e1b9397e.png">

Figma: 
https://www.figma.com/file/GQh990IZ2EaBYZhU93hdi1/TT3%3A-Marigold-Style-Variation?node-id=455%3A426

JSON:
[marigold.json.zip](https://github.com/WordPress/twentytwentythree/files/9457476/marigold.json.zip)

**Comment by critterverse** [comment]
This style variation has been selected to be bundled with the Twenty Twenty-Three default theme! @ beafialho and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes: 

![Marigold](https://user-images.githubusercontent.com/77359364/188936556-de814ec6-1e89-4212-8988-b14bb112b110.png)

- We weren’t sure about the use of DM Sans here, which doesn’t have a light weight and feels a bit round/heavy next to the more delicate Source Serif typeface. Instead, this submission could take some inspiration from @melchoyce's [Soft variation](https://github.com/WordPress/twentytwentythree/issues/151) and use Source Serif throughout for both headlines and paragraph text.

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!
