### ISSUE TITLE
Variation "Aubergine"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#138]
Screenshot:
![Screenshot 2022-08-31 at 09 35 03](https://user-images.githubusercontent.com/20610429/187620623-6cac922a-1360-43e5-b53c-17cccb21d108.png)

Figma:
https://www.figma.com/file/yFcLsr1Hu4ylSnxH61LDOw/TT3-Variation-%22Aubergine%22?node-id=2%3A9

**Comment by beafialho** [comment]
This style variation has been selected to be bundled with the Twenty Twenty-Three default theme! @critterverse and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes:

![Aubergine](https://user-images.githubusercontent.com/65220155/188936645-23ff5459-97e7-41c9-bec6-f32822b3ae20.png)

- We’ve changed the white section on top to be a darker color to help avoid any issues with contrast (in case the white text ever overlaps with that top section)
- We’ve reduced the size and weight of some text and the separators to give everything a slightly more minimal look
- We’ve also applied the same letter spacing on the site title, some headings, and the post dates to align the style better
- We've adjusted the colors slightly to pass accessibility color contrast checks

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!

**Comment by anarieldesign** [comment]
😍 thank u soo much, happy this one will be included 🙏 and can help ❤

**Comment by mikachan** [comment]
Hi @anarieldesign 👋 Is there a JSON file associated with this variation, or does one need to be created?

**Comment by anarieldesign** [comment]
Sorry for the delay @mikachan . We are in Croatia visiting our parents till end of the month so I'm not that much online 🥴. It needs to be created, I made this one in Figma. For some other variations I submitted I had both but this one just Figma file 😅

**Comment by mikachan** [comment]
No worries at all and thanks for replying! Hope you're having a nice time. The JSON file has been created in a PR here: https://github.com/WordPress/twentytwentythree/pull/184
