### ISSUE TITLE
Variation "Lemon"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#139]
Screenshot:
![Screenshot 2022-08-31 at 09 57 33](https://user-images.githubusercontent.com/20610429/187624954-c559a042-5f13-45c8-b082-1f8f2baffcaf.png)

Figma:
https://www.figma.com/file/H2gCH838tgclx6P1zpdMzQ/TT3-Variation-%22Lemon%22?node-id=2%3A9

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
