### ISSUE TITLE
Variation "Portland Orange"

### ISSUE THREAD

**Issue by AdelDima** [WordPress/twentytwentythree#140]
![Homepage](https://user-images.githubusercontent.com/3769804/187628418-ff3e9629-8351-4557-ad1c-b820e1d50b4b.png)
![Colors](https://user-images.githubusercontent.com/3769804/187628665-283a9081-dad1-41dd-8696-9e5478931317.png)
![Buttons and Links](https://user-images.githubusercontent.com/3769804/187628694-78ef2c34-6490-488c-9687-0cc277de44b4.png)

Figma: https://www.figma.com/file/3MwlvpTgVQi8fdId9dgys4/TT3-Portland-Orange?node-id=2%3A9

**Comment by colorful-tones** [comment]
I love the primary color here. 😍

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
