### ISSUE TITLE
Variation "Hannah"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#141]
Screenshot:
![Screenshot 2022-08-31 at 10 29 47](https://user-images.githubusercontent.com/20610429/187633973-58c7fcc2-864f-44bd-9ea9-b8ecebb03849.png)

Figma:
https://www.figma.com/file/W7orTXMZZRHXL4H0I91C85/TT3-Variation-%22Hannah%22?node-id=2%3A9

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
