### ISSUE TITLE
Variation "Botanic"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#142]
Screenshot:
![Screenshot 2022-08-31 at 10 57 59](https://user-images.githubusercontent.com/20610429/187640456-74f04d43-2316-4b08-bf2f-842c34b1503e.png)

Figma:
https://www.figma.com/file/O8RJSwnxQGGSOeTSLwtNwL/TT3-Variation-%22Botanic%22?node-id=2%3A9

**Comment by melchoyce** [comment]
Love these colors!

**Comment by anarieldesign** [comment]
Thank u @melchoyce  ❤

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
