### ISSUE TITLE
Variation "Executive"

### ISSUE THREAD

**Issue by dhanson-wp** [WordPress/twentytwentythree#143]
Still learning Figma, but I really wanted to try my hand at a variation. I love the approach to this year's theme. Thank you all.

<img width="100%" alt="Screen Shot 2022-08-31 at 8 24 19 AM" src="https://user-images.githubusercontent.com/83921778/187694372-39845559-e35e-4bbf-afc3-a1e380f38beb.png">

<img width="100%" alt="Screen Shot 2022-08-31 at 8 32 49 AM" src="https://user-images.githubusercontent.com/83921778/187694525-eda56638-8ea2-4c07-8485-d8a1b56d3649.png">

Figma: https://www.figma.com/file/vGfNJGjpctyha6uauaJ4f2/TT3%3A-Executive?node-id=2%3A9

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
