### ISSUE TITLE
Variation "Scarlet & Gray"

### ISSUE THREAD

**Issue by dhanson-wp** [WordPress/twentytwentythree#146]
Inspired by the start of college football season in the U.S.
<img width="846" alt="Screenshot on 2022-08-31 at 14-52-53" src="https://user-images.githubusercontent.com/83921778/187771217-004869ea-929e-4260-ba40-b7e4c2d12a04.png">

Figma: https://www.figma.com/file/tVNRHAyMQNFNVyJpxsU61R/TT3-Scarlet-%26-Gray-Variation?node-id=2%3A9

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
