### ISSUE TITLE
Variation: "Pumpkin Spice"

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/twentytwentythree#147]
<h1>🌬️ 🌳  <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 🍂 <br> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 🍂 <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 🍂<br> <br>
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 🍂 🍂</h1>

![2023 local_style-guide_](https://user-images.githubusercontent.com/405912/187821068-b7397fd5-00a3-4398-9767-7d6b318e54cd.png)

![2023 local_](https://user-images.githubusercontent.com/405912/187821090-75705f10-b864-407e-bb3a-a039b0f7fc4a.png)

🎃  [spice-latte.zip](https://github.com/WordPress/twentytwentythree/files/9466440/spice-latte.zip)

**Comment by critterverse** [comment]
This style variation has been selected to be bundled with the Twenty Twenty-Three default theme! @ beafialho and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes: 

![Pumpkin Spice](https://user-images.githubusercontent.com/77359364/188936971-854b38db-ba52-4dc5-aa29-d3abf150435c.png)

- We love the details in this submission but noticed some similarity and legibility issues with the palette. Instead, we’re suggesting a light bluish/purple pastel background with a white border around the page.
- The orange accent color could be a rich red
- We’ll probably need to come up with a new name — these color suggestions were loosely inspired by @colin-chadwick's [Dusk variation](https://github.com/WordPress/twentytwentythree/issues/50) in case that inspires any ideas!

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!

**Comment by colorful-tones** [comment]
@critterverse - I've taken a pass at updating the colors and renamed from Pumpkin Spice to Whisper. I'm more than happy to iterate further. See: https://github.com/WordPress/twentytwentythree/pull/154

**Comment by colorful-tones** [comment]
@critterverse I updated a few of the colors to match [the Figma file](https://www.figma.com/community/file/1139275543113752375) you recently updated. The other colors were already matching. I also updated the screenshot in #154 based on these new changes.

**Comment by colorful-tones** [comment]
I'm not sure if it'll make anybody's life easier, but I'm happy to rename this Issue to replace `Pumpkin Spice` with `Whisper.` I'll leave it as is for now, though, as it might be helpful to have the original name for historical purposes.

**Comment by mikachan** [comment]
Closed with https://github.com/WordPress/twentytwentythree/pull/154.
