### ISSUE TITLE
Add a "clear" above the post meta on single posts

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#148]
By chance I ran into a in issue where if a post contains a left aligned image followed by a media and text block, the
post content is not "cleared",  and the post meta area is not the correct width.

Front view
![post meta area is aligned to the right and not below the content](https://user-images.githubusercontent.com/7422055/188081949-a376bbb3-f335-4f78-bcdc-d25e304bd47c.png)

Please see this issue for testing instructions: https://github.com/WordPress/gutenberg/issues/43621

**Comment by carolinan** [comment]
In a quick test, I found that adding a spacer block between the content and the post meta area worked.

**Comment by mikachan** [comment]
I'm not sure if we should handle a fix for this directly in the theme or not. Do you think we should include a spacer block in the template to prevent this from happening?

**Comment by carolinan** [comment]
It needs to be in the theme, because it will break easily with anything that is aligned.

It is a Gutenberg problem, but one that can not be easily solved in Gutenberg because it would drastically change how existing sites look, see example screenshots in https://github.com/WordPress/gutenberg/pull/42910

**Comment by mikachan** [comment]
Ah I see, thanks!
