### ISSUE TITLE
Figma file link not working

### ISSUE THREAD

**Issue by pbking** [WordPress/twentytwentythree#15]
[Twenty Twenty-Three Figma Mockups](https://www.figma.com/file/ohYEHkZzGjOse46NceTfj5/Twenty-Twenty-Three)

The figma file link in the readme file is either not linking to anything or inacessable.  Can this resource be enabled for read-only by default?

<img width="470" alt="image" src="https://user-images.githubusercontent.com/146530/184022147-c5a2b4cb-3dae-4729-9181-c1754ac9f7f7.png">

**Comment by beafialho** [comment]
A new Figma link has been shared in the post: https://www.figma.com/community/file/1139275543113752375
