### ISSUE TITLE
Consider enabling drop cap support

### ISSUE THREAD

**Issue by mikachan** [WordPress/twentytwentythree#150]
TT3 does not currently enable `dropCap` support. This is based on the same reasoning from TT2 (https://github.com/WordPress/twentytwentytwo/issues/180), in that, there is currently a lack of styling control around this feature. It often needs specific typography settings adjusted such as line-height, font-weight, and spacing.

There is an open Gutenberg issue to improve this support (https://github.com/WordPress/gutenberg/issues/36122).

I was wondering if anyone had any thoughts about including this in TT3? We would either need to pursue a fix for the above GB issue, or perhaps we could look into a CSS solution similar to @justintadlock's suggestion [here](https://github.com/WordPress/gutenberg/issues/36122#issuecomment-1031533803). I think something like this solution could work well for TT3, but it obviously involves adding some CSS.

cc. @jasmussen

**Comment by jasmussen** [comment]
I'm a drop-cap fan, it's such a simple little thing, I'd love to have it even if we have to shepard along some extra CSS to go with it. And also because it's an additive enhancement that isn't shown by default:

![add](https://user-images.githubusercontent.com/1204802/188166836-5f1e2b43-f224-408f-8f31-65b25b0f33d1.gif)

But it's not a strong opinion! And I'll happily defer to those of you that do have a strong opinion. 🙏

**Comment by justintadlock** [comment]
I'm a huge fan of drop-caps, at least when they work.  The only way I've been able to somewhat reliably offer support is to use the [JSON + CSS method](https://github.com/WordPress/gutenberg/issues/36122#issuecomment-1031533803), at least if I want to allow others to extend it with custom font-sizes, font-families, or line-heights.

It'd be nice if we could ever get full browser support for `initial-letter`. :)

**Comment by jasmussen** [comment]
I did explore some initial-letter support today, and in theory that really helps line things up in a systematic way so we would need less-to-zero customization options. But even then the Safari implementation felt very barebones, and didn't _always_ line up. So unfortunately that one's still on the wishlist 🌃

**Comment by colorful-tones** [comment]
I'm all for the option of Drop Cap support, but not sure how it could be implemented in TT3. I have not tested in a while, but it might be ideal to have `"dropCap": false` in the parent `theme.json` and then if a style variation wants to have `"dropCap": true` and then the `"custom"` entries then this seems like a nice compromise. Of course, we would have to put the default variables in the theme's `styles.css` from @justintadlock example:

```
.has-drop-cap:not(:focus)::first-letter {
	font-family: var( --wp--custom--drop-cap--typography--font-family, inherit );
	font-size: var( --wp--custom--drop-cap--typography--font-size, 5.5em );
	font-weight: var( --wp--custom--drop-cap--typography--font-weight, 700 );
	font-style: var( --wp--custom--drop-cap--typography--font-style, normal );
	line-height: var( --wp--custom--drop-cap--typography--line-height, .85 );
	margin: var( --wp--custom--drop-cap--spacing--margin, 0.05em 0.1em 0 0 );
	padding: var( --wp--custom--drop-cap--spacing--paddig, 0 );
}
```

**Comment by mikachan** [comment]
Closing as the theme has been merged into the WordPress Core SVN repository and is no longer maintained on GitHub.
