### ISSUE TITLE
Variation: Soft

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentythree#151]
![image](https://user-images.githubusercontent.com/2846578/188215956-bb164982-ff4b-42b0-a4c0-aa17c9af04a2.png)
![image](https://user-images.githubusercontent.com/2846578/188215973-3d3e1f7a-bb65-4dff-8406-e28b68fdad9d.png)

![image](https://user-images.githubusercontent.com/2846578/188217952-028c9a59-20bb-4802-bad3-919b784616f8.png)
![image](https://user-images.githubusercontent.com/2846578/188217960-f8233e22-ca9c-4b70-b78d-46f612fce033.png)

[Figma](https://www.figma.com/file/u8qzWHo65YuqXF7Vgbk7xm/Twenty-Twenty-Three-(Community)?node-id=403%3A768)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
