### ISSUE TITLE
Variation: "Canary" (previously Example 2)

### ISSUE THREAD

**Issue by critterverse** [WordPress/twentytwentythree#152]
Example 2 has been selected to be bundled with the Twenty Twenty-Three default theme! @beafialho and I have made some tweaks to the submission as a part of the curation process to ensure that all the selected variations work together nicely as a collection. Here are the requested changes: 

![Canary](https://user-images.githubusercontent.com/77359364/188935755-b1e45ed8-fae4-4e9b-ba23-7d31b9a0c366.png)

- The single type size used throughout the design is a cool effect but it could be even more opinionated if the universal type size was a bit smaller
- With the smaller type size, it would be interesting to try the layout using a really narrow center column
- Let’s incorporate an asymmetrical border radius effect inspired by @melchoyce's [Mono submission](https://github.com/WordPress/twentytwentythree/pull/144)
- Let’s try a brighter yellow for the background color
- Canary could be a good name for this one!

No explicit next steps are needed — feel free to update theme.json files where relevant or they will be updated in development. Thanks for the contribution!

**Comment by beafialho** [comment]
Here's the updated theme.json file from "Canary".

[canary.json.zip](https://github.com/WordPress/twentytwentythree/files/9558288/canary.json.zip)

- Set a smaller type size
- Set a more narrow center column
- Added an asymmetrical border radius effect
- Set a brighter yellow for the background color
- Named it "Canary"

**Comment by mikachan** [comment]
Closed as part of https://github.com/WordPress/twentytwentythree/pull/169.
