### ISSUE TITLE
Using Adobe web fonts in theme.json

### ISSUE THREAD

**Issue by flexseth** [WordPress/twentytwentythree#162]
## What problem does this address?

Background: As an Adobe Creative Cloud subscriber, I pay for access to this web font so I do not want to have to pay to download the font to install it on a WordPress 6.0+ website.

![cXWYmLGHziPecoTjPTDzrJ5J](https://user-images.githubusercontent.com/3792502/189573277-a42a4cbc-c77b-4ec6-bf5c-7b7649aef2db.png)

https://fonts.adobe.com/fonts/carta-marina

## Example theme.json style
Via Rich Tabor's "Pitch" style variation for Twenty Twenty Three 
https://raw.githubusercontent.com/WordPress/twentytwentythree/20c9a2b1300e2b7d3147c6f1f922d4a687891f47/styles/pitch.json

### Existing Syntax for an "installed" web font

```json
{
	"fontFamily": "DM Sans",
	"fontStretch": "normal",
	"fontStyle": "normal",
	"fontWeight": "700",
	"src": [
		"file:./assets/fonts/dm-sans/DMSans-Bold.woff2"
	]
},
```

## Proposed syntax for "hosted" web font
Allow linking via web font CDN

```json
{
	"fontFamily": "carta-marina, sans-serif",
	"fontStretch": "normal",
	"fontStyle": "normal",
	"fontWeight": "400",
	"src": [
		"https://use.typekit.net/dj299sl.css"
	]
},
```

**Comment by carolinan** [comment]
Hi! This part of the font api is not complete. It is not planned to support remote font providers in WordPress 6.1.
You can follow the progress in updating the api for 6.1 here: https://github.com/WordPress/gutenberg/pull/43492

**Comment by luminuu** [comment]
Something to remember is that in default themes, no external font resources should be used in order to comply with GDPR. See the following posts:
https://make.wordpress.org/themes/2022/06/18/complying-with-gdpr-when-using-google-fonts/
https://make.wordpress.org/themes/2022/07/28/using-locally-hosted-google-fonts-in-themes/

**Comment by flexseth** [comment]
Ah, I see. It looks like to correctly comply with GDPR you must have the font installed on the remote host of the website? I don't believe you can do that anymore with Adobe (Typekit had this option), now Adobe web fonts are hosted via Typekit CDN at use.typekit.net

https://helpx.adobe.com/fonts/using/use-typekit-net.html

Implementing Webfonts API mentions Adobe
https://make.wordpress.org/core/2021/09/28/implementing-a-webfonts-api-in-wordpress-core/

But it looks like they are looking for a font handle, which isn't explicitly provided via Adobe. It could very well just be font-name-here standard, where that's the name of the font converted to dash delimited. 

If the WP docs could be updated to illustrate how to use Adobe fonts and comply to with GDPR, that would be huge. Also: Does enqueuing fonts in this way comply with GDPR? If so, maybe I can make a contribution!! 

Although enqueuing the font without having it installed on the web host (or not having the font installed?) appears to be the issue with GDPR compliance? If you intel on that it would be very helpful..

Edited to note are any of these Embed codes GDPR compliant? How would one know..
https://helpx.adobe.com/fonts/using/embed-codes.html

**Comment by carolinan** [comment]
Please refer to your legal council to confirm if something complies with GDPR.

**Comment by colorful-tones** [comment]
@flexseth the capabilities of including an externally hosted font do not currently exist for block themes (within the `theme.json`).

The roadmap for these APIs lie within the Gutenberg project: https://github.com/WordPress/gutenberg/issues/41479

For the purpose of this theme that will ship with the upcoming WordPress 6.1 release (estimated for early November) it is not feasible for those APIs to be built in time given the complexity  and breadth of features outlined in that 👆 roadmap.

Certainly, the idea of allowing users to be able to include their paid fonts is a great feature and we will get there. It is just not ready for block themes.

Also, I believe this theme will likely ship with the existing fonts and is not looking to include additional families (e.g. Carta Marina).

Once this theme is launched in the upcoming 6.1 release then I'm sure you could certainly create a [child theme](https://developer.wordpress.org/themes/advanced-topics/child-themes/) and include your font using the existing APIs. Here is a good example: https://gist.github.com/robneu/6400399

I would recommend we close this issue for now unless you would like further clarification?

**Comment by flexseth** [comment]
@colorful-tones & @carolinan  - I see, this makes sense. Understandably there are a lot of undertakings with the Gutenberg project that provide more ROI for the platform as a whole. Maybe a solution would be to purchase the web font and enqueue it that way - while you could still design and do local development with the Adobe web fonts. 

Just wanted to mention this, it was really more of a feature request than an issue :) 

Thank you @luminuu on the thoughts on GDPR. Not legal advice, but I think if you can install the web fonts on the server by purchasing them after design time, you could still be complaint. 

Marking this as resolved, did want to put the discussion out there, though!

Best/Seth

**Comment by colorful-tones** [comment]
> Maybe a solution would be to purchase the web font and enqueue it that way - while you could still design and do local development with the Adobe web fonts.

Yes, this should work fine. However, it would not likely be a feature considered for this project. 

This GitHub project represents a theme which will be included in the larger WordPress core project. The font would have to be compatible with GPL licensing. That would require it to be SIL Open Font Licensed (OFL). Also, I'm not sure how and who would purchase the font to include it in a theme that will be distributed across a large population and formats.

> install the web fonts on the server by purchasing them after design time, you could still be complaint.

Yes, I believe that would likely avoid the GDPR issue. 👍
