### ISSUE TITLE
Only one post date format is translation ready

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#167]
In single posts, the post date format is inside a block pattern and uses a translation function:
`<!-- wp:post-date {"format":"<?php echo esc_html_x( 'F j, Y', 'Date format for publication date of post', 'twentytwentythree' ); ?>"} /-->`

In archives/blog/search the post date format can not be translated because it is hard coded:
`	
			
			
			
			
			
			<div style="height:var(--wp--preset--spacing--50)" aria-hidden="true" class="wp-block-spacer"></div>
			
		
`

This means that the date format can end up being different on different parts of the website.
Perhaps it is better to remove the translation function from the pattern, and let the user update it per template, and save the template changes.

**Comment by mikachan** [comment]
Thanks for bringing this up, it's not great if the date format ends up being different across different places in the theme. 

> Perhaps it is better to remove the translation function from the pattern, and let the user update it per template, and save the template changes.

I think this is probably the best option for now.
