### ISSUE TITLE
Variation: "Electric" (previously Example 3)

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentythree#168]
Screenshot: 
![Homepage](https://user-images.githubusercontent.com/65220155/190676176-2436185a-75ef-4994-89e1-ece2417d6e15.png)

![Single Post](https://user-images.githubusercontent.com/65220155/190675979-8c4605bd-5e3b-4d34-9b0e-15e60363ec4f.png)

Figma: https://www.figma.com/community/file/1139275543113752375

**Comment by colorful-tones** [comment]
😍

[![Electric Boogie](https://img.youtube.com/vi/5jBkoEM0SSE/0.jpg)](https://www.youtube.com/watch?v=5jBkoEM0SSE)
