### ISSUE TITLE
Update theme description

### ISSUE THREAD

**Issue by mikachan** [WordPress/twentytwentythree#177]
We should update the theme description in the readme.txt and style.css files.

@beafialho @critterverse do we already have some copy for this?

Here is the description from TT2 as an example:

> Built on a solidly designed foundation, Twenty Twenty-Two embraces the idea that everyone deserves a truly unique website. The theme’s subtle styles are inspired by the diversity and versatility of birds: its typography is lightweight yet strong, its color palette is drawn from nature, and its layout elements sit gently on the page.

> The true richness of Twenty Twenty-Two lies in its opportunity for customization. The theme is built to take advantage of the Full Site Editing features introduced in WordPress 5.9, which means that colors, typography, and the layout of every single page on your site can be customized to suit your vision. It also includes dozens of block patterns, opening the door to a wide range of professionally designed layouts in just a few clicks.

> Whether you’re building a single-page website, a blog, a business website, or a portfolio, Twenty Twenty-Two will help you create a site that is uniquely yours.

**Comment by beafialho** [comment]
Sure, here it is:

> Twenty Twenty-Three is a diverse, collaborative effort designed with the expansion of the possibilities of the block editor in mind. With a blank, unopinionated base as a starting point, this year’s default theme has minimal demo content to get in your way.
> 
> It embraces aesthetic diversity with a collection of style variations created by members of the WordPress Community, and it is built to take advantage of the new tools introduced in WordPress 6.1.
> 
> Whether you want to build a complex or incredibly simple website, you can style it the way you want it, and you can do it quickly and intuitively through the bundled styles or dive into creation and full customisation yourself.

**Comment by mikachan** [comment]
Thank you!
