### ISSUE TITLE
Post meta pattern in Page types

### ISSUE THREAD

**Issue by dashkevych** [WordPress/twentytwentythree#178]
By default, when creating a page (`page.html`), the page does not display a post meta (with information about date, author, tags) section under the content. 

And I guess it's good because post meta section is more relevant to Post types rather than Page types.

However, when changing template to a page with featured image (`with-featured-image.html`), or to a page with cover block (`with-cover-block.html`), the page displays the post meta section under the content.

I am wondering if it's done intentionally, or is it a bug?

Page with default template:

<img width="1792" alt="page-with-default-template" src="https://user-images.githubusercontent.com/3655965/191080788-207985d5-f0dc-42b7-ba62-8374d129ae8c.png">

Page with featured image template:

<img width="1792" alt="page-with-featured-image-template" src="https://user-images.githubusercontent.com/3655965/191080803-5e65f3ce-f11b-46cb-82b5-d8bc8a233366.png">

**Comment by carolinan** [comment]
The meta info is a pattern, but I don't think it is possible to use `is_page()` since patterns do not have access to `global $wp_query;`.
So if you want this to be included for posts but not pages, the theme needs two different templates.

**Comment by dashkevych** [comment]
It seems like Gutenberg allows to display patters based on selected post type (https://github.com/WordPress/gutenberg/issues/41398) but it does not work yet for patters created with PHP header tags.

**Comment by dashkevych** [comment]
> So if you want this to be included for posts but not pages, the theme needs two different templates.

I am wondering how `twentytwentythree` theme is going to solve this issue. Leaving it "as is" might cause some problems:

1) It can increase support requests from WordPress users, since Page post type does not allow to add tags/categories. As a result, the post meta section will look uncompleted in pages with those templates.
2) Above, can negatively affect rating of the theme in WordPress repository.

**Comment by carolinan** [comment]
Because of how the text is added, the "Tags" text will always show also on posts that have no tags.

**Comment by mikachan** [comment]
> I am wondering how twentytwentythree theme is going to solve this issue.

We will hopefully be consolidating the single templates into one post template: https://github.com/WordPress/twentytwentythree/pull/172. This would mean that the post meta would not be included on the page template by default.

If we're unable to land the above PR, then I think we'd be best doing what @carolinan suggested above and creating two different templates.
