### ISSUE TITLE
Collect missing .org usernames

### ISSUE THREAD

**Issue by desrosj** [WordPress/twentytwentythree#180]
Several contributors are missing .org usernames in CONTRIBUTORS.md. To be mentioned on the 6.1 About page and related release posts, a wp.org username is needed.

@bobmatyas, @hiyascout, @Dabalina, @kathryncodes, @nudgeD, @WBerredo: Could you share your WordPress.org usernames please?

**Comment by Dabalina** [comment]
I'm dll416 on WordPress.org

Thanks!

**Comment by bobmatyas** [comment]
I'm "lastsplash" on WordPress.org.

**Comment by nudgeD** [comment]
I'm "nudge" on WordPress.org

**Comment by WBerredo** [comment]
I'm "wberredo" on WordPress.org

**Comment by kathryncodes** [comment]
I'm kathryncodes on Wordpress.org 

Thanks!
