### ISSUE TITLE
Styles: Have more variations that don't offset Post Title

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#186]
In most of the style variations (9 out of 10), the Post Title block is set to use Wide alignment and be left-aligned, which offsets it to the left of the content below it on desktop – like this, for example:

![Editor__beta__‹_Twenty_Twenty-Three_Testing_—_WordPress](https://user-images.githubusercontent.com/7662449/191330684-ac61fe59-d5d9-4532-9bfd-aed6f567e843.jpg)

In my experience working with WordPress users, a lot of folks often don't like things that are offset from the content like this, as it can look unbalanced. Instead, many people prefer to have the post/page title either aligned with the content below it, or centered above it. In the past, this usually took custom CSS to achieve, but with FSE they can now de-select the Wide alignment option instead in the Page and Single templates. I'll certainly [document that route](https://github.com/WordPress/Documentation-Issue-Tracker/issues/441), but I'm still concerned that this manual avenue isn't going to be intuitive or obvious to many folks.

Could we perhaps consider modifying at least a couple of the variations so that the title is aligned with the content, or centered? Examples would look like:

![Editor__beta__‹_Twenty_Twenty-Three_Testing_—_WordPress](https://user-images.githubusercontent.com/7662449/191331628-5d8964ce-fd50-424a-a8bb-383ba8efe7a5.jpg)

![Editor__beta__‹_Twenty_Twenty-Three_Testing_—_WordPress](https://user-images.githubusercontent.com/7662449/191331784-36b9e9c9-db30-4bdc-882c-ffe136e520b9.jpg)

This would also help provide a bit more layout variety when users are browsing Styles.

Thanks for considering!

**Comment by carolinan** [comment]
This is not possible to do with style variations.
Theme.json can not be used to align blocks to left/right/center/none/wide or full.
Please see https://github.com/WordPress/gutenberg/issues/44007

It can only be achieved in the template or with custom CSS (it was decided not to use CSS).

**Comment by kathrynwp** [comment]
Oh interesting, thanks for letting me know, @carolinan! 

Could we perhaps consider a different method, such as what the yellow-background variation did. It's the only one of the ten variations to have the post title aligned with the content. I see that the Post Title block is still set to Wide alignment, but the width is defined as 650px:

![Editor__beta__‹_Twenty_Twenty-Three_Testing_—_WordPress](https://user-images.githubusercontent.com/7662449/191353386-0486a5dc-5961-4443-b068-1937d129c4ef.jpg)

**Comment by mikachan** [comment]
> Could we perhaps consider a different method, such as what the yellow-background variation did. 

This variation (Canary) is setting the `settings.layout.wideSize` to 650px, which is why the post title is aligned with the content here. So in order to replicate this, we'd need to set this smaller wideSize width on more variations, which will probably have significant affects on the rest of the variation.

@beafialho, do you think any of the current variations would work well with the reduced wideSize content width, similar to Canary?

Alternatively, there are plans to continue building more variations for TT3 beyond the WP 6.1 release (for fun/learning etc!), perhaps we could consider trying this out then?

**Comment by mikachan** [comment]
I'm going to close this as we removed the wide alignment used on page and post titles as part of https://github.com/WordPress/twentytwentythree/pull/272, so I don't believe any titles are now offset.
