### ISSUE TITLE
Variations in Site Editor: `<body>` styling clipped

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/twentytwentythree#195]
This is affecting the following variations in the site editor: Pilgrimage (body background gradient), Sherbet (body background gradient), Whisper (body border). I'm not seeing an upstream Gutenberg issue for this and will likely create one tomorrow.

**Pilgrimage** (body background gradient cut off in iframe)
<img width="1397" alt="Screen Shot 2022-09-22 at 8 55 28 AM" src="https://user-images.githubusercontent.com/405912/191754054-54b137b8-fad4-4899-a704-60d265a63040.png">

**Sherbet** (body background gradient cut off in iframe)
<img width="1393" alt="Screen Shot 2022-09-22 at 8 56 20 AM" src="https://user-images.githubusercontent.com/405912/191754234-d4d6a51c-36e2-4ffe-b2ed-880f2dec1be3.png">

**Whisper** (body border cut off in iframe)
<img width="1387" alt="Screen Shot 2022-09-22 at 8 56 34 AM" src="https://user-images.githubusercontent.com/405912/191754258-096bcc09-56c4-48da-a717-efd2446dda5e.png">

**Comment by mikachan** [comment]
Closing this, as an upstream issue was created [here](https://github.com/WordPress/gutenberg/issues/44374).
