### ISSUE TITLE
Update text casing of site-title

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/twentytwentythree#198]
Update the site-title casing in the following variations.

- [x] Pilgrimate: make font style italic https://github.com/WordPress/twentytwentythree/pull/226
- [x] Marigold: transform to lowercase https://github.com/WordPress/twentytwentythree/pull/226
- [x] Block out: transform to lowercase - Fixed in #196 
- [x] Whisper: transform to capital case https://github.com/WordPress/twentytwentythree/pull/226
- [x] Grapes: transform to lowercase https://github.com/WordPress/twentytwentythree/pull/226

**Comment by mikachan** [comment]
I don't think the Marigold site title should be lowercase, based on the designs here: https://github.com/WordPress/twentytwentythree/issues/137

**Comment by madhusudhand** [comment]
> I don't think the Marigold site title should be lowercase, based on the designs here: #137

The refined design suggests a lower case https://github.com/WordPress/twentytwentythree/issues/137#issuecomment-1239673232

**Comment by mikachan** [comment]
Ah, OK! Thanks for pointing that out. I've added that change to https://github.com/WordPress/twentytwentythree/pull/226.
