### ISSUE TITLE
Blocks style in the editor does not match the frontend's blocks style

### ISSUE THREAD

**Issue by amjadr360** [WordPress/twentytwentythree#202]
For some blocks `blocks/***/theme.min.css` is used to keep consistency across the UI(editor/frontend) and `add_theme_support( 'wp-block-styles' );` is used to add `theme.min.css`'s CSS as inline-CSS at fronted. As Twenty Twenty Three theme no longer uses `functions.php`.

Before I open any PR, I want to discuss solutions to keep consistency across the UI. 

- Adding back `functions.php` for this only not seems a good idea.
- Adding custom CSS is not a good idea. 
- Moving `blocks/***/theme.min.css` CSS to `blocks/***/style.scss`. Might be. But backward compatibility. 
- Improve those blocks style that uses 'theme.min.css`. Yes, this soulation LGTM.

Here are blocks that have style consistency issues.

![image](https://user-images.githubusercontent.com/32260742/192069827-7485fc17-0f66-4b19-8db1-d9de339c0536.png)
![image](https://user-images.githubusercontent.com/32260742/192070972-892af61e-87c0-4447-97f3-409814d891bf.png)

**Comment by carolinan** [comment]
I would expect those styles to not be loaded in the editor unless the theme supports wp-block-styles. I think this is a Gutenberg bug or even possibly a regression.

**Comment by carolinan** [comment]
Also, I see that these images use the theme test data. That XML file is not up to date with the current block markup.

**Comment by aristath** [comment]
Looking at the code, I can see that if `$editor_styles` is empty, we load `wp-block-library-theme` as a dependency for `wp-edit-blocks` style. Perhaps we should remove the dependency from there? (in `client-assets.php`)

**Comment by mikachan** [comment]
https://github.com/WordPress/gutenberg/pull/44640 may fix this issue 🎉

**Comment by mikachan** [comment]
I believe these issues have been fixed by https://github.com/WordPress/gutenberg/pull/44640.
