### ISSUE TITLE
Remove separator from home template

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentythree#205]
We should remove this separator from the template. It made sense if there was post navigation but it just feels like it's floating without it.

<img width="1402" alt="Captura de ecrã 2022-09-26, às 13 20 28" src="https://user-images.githubusercontent.com/65220155/192274770-128d88f5-41f1-4568-a3fc-8e282c8ef30e.png">

**Comment by mikachan** [comment]
The post navigation block is still underneath this separator:

![image](https://user-images.githubusercontent.com/1645628/192292188-65da6452-0a97-4871-948b-0e8e363bdf63.png)

Have you maybe not got enough posts to trigger the post navigation, or have you changed your reading settings?

**Comment by beafialho** [comment]
Oh, I see. I currently have 6 posts. I think 3 should be enough to show the post navigation 🤔 

Would it be possible to omit the separator if there aren't enough posts to show the navigation? Those two clash a bit.

**Comment by mikachan** [comment]
Hmm yeah, 6 should be enough to show the navigation I would've thought, although it may depend on your reading settings at Reading > Blog pages show at most. Maybe try reducing this number.

> Would it be possible to omit the separator if there aren't enough posts to show the navigation? 

I've just been playing about with this - I thought moving the separator block into the query pagination block would do the trick, but if I do this the separator renders at 0px width and so it doesn't show. This is an upstream bug - I'll see if I can find an issue for it.

**Comment by beafialho** [comment]
> although it may depend on your reading settings at Reading > Blog pages show at most. Maybe try reducing this number.

Yes, you're correct. I guess that will really depend on the settings each user has then 🤷🏼‍♀️ 

> This is an upstream bug - I'll see if I can find an issue for it.

Thank you.

**Comment by mikachan** [comment]
I've opened an issue for this: https://github.com/WordPress/gutenberg/issues/44587

I tried playing around with a few different things to try and get it working, but I think we need either a CSS or markup fix in Gutenberg.

**Comment by carolinan** [comment]
Was there any attempt to add a top border to the query pagination instead?
