### ISSUE TITLE
Make footer-credit text size smaller than body text size

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#208]
Users normally expect footer-credit text to be smaller than the body text size. Since the footer credit is much less important than the main body copy, the vast majority of people usually want it to be less prominent visually than the body text.

Could we consider reducing the default size of the footer-credit text in the variations where it's currently the same size as the body text, so that people don't need to manually reduce the size?

Example from the black-background variation:

![Twenty_Twenty-Three_Testing_–_Just_another_WordPress_site](https://user-images.githubusercontent.com/7662449/192330351-7c37f3c1-8843-4bd4-8872-b9c79c3c78d7.jpg)

The red-background variation also has a secondary issue, where the site title in the footer area is way larger than the "Powered by" message:

![Twenty_Twenty-Three_Testing_–_Just_another_WordPress_site](https://user-images.githubusercontent.com/7662449/192330824-3bb31313-a299-43dc-9def-f35c7681e6f8.jpg)

Thanks for having a look!

**Comment by mikachan** [comment]
One of the issues we have here is that we're not able to target the footer area via theme.json, so it's only the base theme that can influence the footer font size. 

We opted against including opinionated styles in the templates, but for this, we could consider adding a specific font size to the blocks in the footer. The computed font size would depend on the selected variation, but if we chose for example 'small', it would be smaller than the default font size of 'medium'.

**Comment by beafialho** [comment]
I suggest we keep the footer size for consistency in the theme. The original intention in the design was to have the same font size in header and footer. While I understand the reason of the suggestion, users can easily change the font size if they wish to or replace the footer pattern.

**Comment by mikachan** [comment]
Thanks @beafialho!
