### ISSUE TITLE
Whisper Style thumbnail has white space around it, causing scrolling

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#209]
The Whisper variation thumbnail has white space all around it, causing vertical scrolling:

![Editor__beta__‹_Twenty_Twenty-Three_Testing_—_WordPress](https://user-images.githubusercontent.com/7662449/192333892-bb41538d-947e-489c-9aa6-a8d78fedbd7a.jpg)

Tested with:

WP 6.1 (latest nightly via Beta Tester plugin), Local install
TT3 download from Github
Firefox 104.0.2 / Safari 16.0 / Chrome 105.0.5195.125
MacOS 12.6

**Comment by mikachan** [comment]
Thanks for reporting this!

The Whisper variation has an intentional white border around the outside, and it looks like the variation preview isn't handling it well. I'll look for / open an issue for this in Gutenberg.

**Comment by ndiego** [comment]
I have put together a fix for this here: https://github.com/WordPress/gutenberg/pull/44556

**Comment by mikachan** [comment]
Closing this as https://github.com/WordPress/gutenberg/pull/44556 has been merged. Thank you!
