### ISSUE TITLE
Add page-excerpt support

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#210]
Since the Query Loop block supports displaying Pages, could we consider supporting Page excerpts in this theme?

Compare how the Query Loop block looks with posts that have excerpts:

![Query_Loop_–_Twenty_Twenty-Three_Testing](https://user-images.githubusercontent.com/7662449/192361431-220944a4-da5c-4dbb-bce1-95659d97c3d2.jpg)

Versus how the same block looks with pages, which don't currently support excerpts:

![Query_Loop_–_Twenty_Twenty-Three_Testing](https://user-images.githubusercontent.com/7662449/192361527-d92a7186-d637-45b5-afc9-b10c0f7591ec.jpg)

Users will be able to create nicer-looking layouts if the theme supports page excerpts.

Thanks for considering!

**Comment by mikachan** [comment]
Hmm, this is the first time I've looked into page excerpts with the Query Loop block, but I imagine this is because of the version of the page excerpt the block is using, rather than what the theme is opting into. I'll add a Gutenberg label for now, and do some more testing soon. Will report back!

**Comment by carolinan** [comment]
Page excerpts are plugin functionality that are not suitable for themes, this is because if you add an excerpt and then switch themes, you can no longer edit or delete that excerpt (not without installing another theme or plugin that registers excerpt for pages).

**Comment by mikachan** [comment]
Thanks, @carolinan. I'll close this issue based on that info.
