### ISSUE TITLE
Style variation Electric: button hover shifts the other contents

### ISSUE THREAD

**Issue by tahmidulkarim** [WordPress/twentytwentythree#213]
When the button "Get in Touch" is hovered it shifts the contents at the top and bottom of the button.

Here is a video - https://drive.google.com/file/d/1HHDBhe2dP1ApQu3luQBbdfdmu920GSsZ/view

**Comment by mikachan** [comment]
Closed with https://github.com/WordPress/twentytwentythree/pull/215.
