### ISSUE TITLE
Fluid typography and Mobile Navigation button do not work on WP 6.1

### ISSUE THREAD

**Issue by ya123123** [WordPress/twentytwentythree#214]
1. Theme.json fluid is true, but output font size presets are not fluid values.

![n1625](https://user-images.githubusercontent.com/114547428/192722885-47ce937f-8063-452c-baf6-268561a16ec2.png)

2. Nothing happens when I click the mobile navigation button (the menu doesn't pop up).

![n1629](https://user-images.githubusercontent.com/114547428/192724100-056f0d95-0073-4de3-95d3-29c7e36f93fb.png)

Tested with:
WP 6.1 (latest nightly via Beta Tester plugin), instawp install
TT3 included in WP 6.1 nightly.
Chrome 106.0.5249.62
Windows 10

Sorry if here is not the right place to report.

**Comment by ramonjd** [comment]
I suspect this will be fixed in https://github.com/WordPress/wordpress-develop/pull/3362

**Comment by desrosj** [comment]
Hi @mayuge3! Thanks for your recent bug reports!

If you don't mind, could you create a wordpress.org account (if you haven't already) and link it to your GitHub one following the instructions here: [Associating GitHub accounts with WordPress.org profiles](https://make.wordpress.org/core/2020/03/19/associating-github-accounts-with-wordpress-org-profiles/)

This will help ensure that you receive proper attribution (which is based on wp.org usernames) when your contributions (which bug reports are absolutely considered) when new versions of WordPress are released.

**Comment by ya123123** [comment]
Thank you @desrosj !
I made an account @mayuge on WordPress.org and linked my GitHub.

**Comment by mikachan** [comment]
Closing as will be fixed by https://github.com/WordPress/wordpress-develop/pull/3362.

**Comment by ya123123** [comment]
@mikachan 
Fluid typography now works on the latest nightly WP 6.1-beta2-54363, thank you!

However, the mobile navigation button still does not work without gutenberg plugin. Should I wait for more updates or create a new issue?

**Comment by mikachan** [comment]
Thank you for clarifying this! It could be that this is being fixed by another update, but it sounds like https://github.com/WordPress/wordpress-develop/pull/3362 didn't cover it. It may be worth opening a new issue in the Gutenberg repo.

@ramonjd, do you know if the issue with the responsive navigation button not working without Gutenberg may be fixed in an existing PR? (I'll also see if I can find a related issue/PR.)

Edit: I've opened an issue here: https://github.com/WordPress/gutenberg/issues/44638

**Comment by mikachan** [comment]
Following up on the above: the navigation overlay button should be fixed in 6.1 Beta 3 with https://github.com/WordPress/wordpress-develop/pull/3395 🎉

**Comment by ya123123** [comment]
The navigation overlay button now works in 6.1 beta3. Thank you!
