### ISSUE TITLE
The "no results" text is not translation ready

### ISSUE THREAD

**Issue by YanCol** [WordPress/twentytwentythree#217]
In the search.html template, the text inside the query-no-results block "Sorry, but nothing matched your search terms. Please try again with some different keywords" isn't a translatable string.
https://github.com/WordPress/twentytwentythree/blob/trunk/templates/search.html#L31

**Comment by mikachan** [comment]
Thanks for reporting this! I've opened a PR that hopefully fixes it: https://github.com/WordPress/twentytwentythree/pull/222

**Comment by mikachan** [comment]
@YanCol, do you have a WordPress.org account? If not, would you mind creating one? This is so you can be successfully listed as a contributor on both GitHub and WordPress.org. Thanks!

**Comment by YanCol** [comment]
@mikachan Yes I'm [@collet](https://profiles.wordpress.org/collet/) on WordPress.org. Thank you very much!
