### ISSUE TITLE
Add `accessibility-ready` tag

### ISSUE THREAD

**Issue by mikachan** [WordPress/twentytwentythree#218]
It would be great if we could add the `accessibility-ready` tag to this theme.

Based on the conversation around adding this tag to TT2 in the [trac ticket here](https://core.trac.wordpress.org/ticket/55172), I believe the tag could also be added to TT3.

Opening this issue in case anything is blocking this (maybe https://github.com/WordPress/twentytwentythree/issues/182, but these should all be fixed soon), and to serve as a reminder to add the tag.

**Comment by carolinan** [comment]
The theme needs to be checked against these requirements:
https://make.wordpress.org/themes/handbook/review/accessibility/required/

**Comment by mikachan** [comment]
I've been through the base theme and each variation, checking the above accessibility requirements using Firefox's accessibility debug tools. I've found the following issues:

### Content Links ([requirements](https://make.wordpress.org/themes/handbook/review/accessibility/required/#content-links))
- [x] Canary (no underline) https://github.com/WordPress/twentytwentythree/pull/259

### Contrasts ([requirements](https://make.wordpress.org/themes/handbook/review/accessibility/required/#contrasts))
- [x] Block out: active link state https://github.com/WordPress/twentytwentythree/pull/264
- [x] Aubergine: active link state https://github.com/WordPress/twentytwentythree/pull/264
- [x] Aubergine: active, focus, hover button states https://github.com/WordPress/twentytwentythree/pull/264
- [x] Marigold: active link state https://github.com/WordPress/twentytwentythree/pull/264
- [x] Marigold: button hover state https://github.com/WordPress/twentytwentythree/pull/264

**Comment by chakrinya009** [comment]
can you please assign this issue

**Comment by mikachan** [comment]
Hi @chakrinya009, thanks for offering to help! All the issues listed here have either been merged already or are included in https://github.com/WordPress/twentytwentythree/pull/264. You could help by testing out https://github.com/WordPress/twentytwentythree/pull/264, if you like.

**Comment by robglidden** [comment]
In RC1, the buttons are nearly unreadable for at least 2 styles - Aubergine and Pilgrimage.

To recreate this I used the Theme Unit Data, and looked at the "Block: Button" post.

The buttons of one of the other darker styles, Pitch, seem reasonable from just looking, though I did not do an accessible contrast check on them.

My guess from inspecting with Chrome devtools and checking the theme.json files is that these styles are using different color combinations (primary, base, contrast, tertiary, secondary etc) for their button styles.

**Comment by robglidden** [comment]
Although closed by #270, image of aubergine style:

<img width="1131" alt="CleanShot 2022-10-11 at 16 44 09@2x" src="https://user-images.githubusercontent.com/2780622/195218625-f1d86654-b802-4568-86cc-cefccbabc1cb.png">

**Comment by mikachan** [comment]
Thanks for posting this, @robglidden. Could you tell me what colour you're seeing in the browser debug tools for button text in Aubergine? It should be `var(--wp--preset--color--base)`, or `#1B1031`.

**Comment by carolinan** [comment]
> To recreate this I used the Theme Unit Data, and looked at the "Block: Button" post.

The button block markup in this test is very old. Unless you opened the page in the editor, updated the blocks and saved, you might get a different result when you add a button with the current markup.
(This is why there is a big need for automated test content where the blocks are always up to date)

**Comment by robglidden** [comment]
Yes, the post "Block: Button" is unedited and straight from the Theme Unit Data at https://codex.wordpress.org/Theme_Unit_Test.

The devtools screenshot below shows var(--wp--preset--color--base) #1B1031 is being overridden.

<img width="1093" alt="CleanShot 2022-10-11 at 22 34 51@2x" src="https://user-images.githubusercontent.com/2780622/195258851-7fe442f2-5fc7-4dda-a4e9-1beb64b9d31c.png">

**Comment by carolinan** [comment]
Thank you, then I was right, it is not the actual theme but the test data that is the issue.

This markup does not contain the wp-element-button CSS class, because the markup is too old.

**It is unfortunate but this will keep affecting users that have content created before the button block was updated, unless they also open each page/post with buttons and saves the new markup.**

**Comment by robglidden** [comment]
Yup, I just now opened the "Block: Button" post, dated 2018, in the editor, made an unrelated change, and saved. Button text color now as expected.

Seems like the Theme Unit Data may be overdue for a similar update by reopening and saving relevant posts.
