### ISSUE TITLE
Add caption styles in theme.json

### ISSUE THREAD

**Issue by ndiego** [WordPress/twentytwentythree#219]
I think it would be worthwhile to add caption styles in theme.json. In doing a bit of testing, there is a good amount of visual inconsistency between the Editor and Frontend. This is due to Editor specific styles that do not get loaded on the Frontend, which is a separate issue in my opinion. But until that is address/discussed in Gutenberg, simply adding theme-specific caption styles in theme.json would solve this. 

**Editor:**

![image](https://user-images.githubusercontent.com/4832319/192927213-612b4046-ebbf-4b5a-9681-6fdcfdb7a081.png)

**Frontend:**

![image](https://user-images.githubusercontent.com/4832319/192927244-fb47d5a1-5896-4cad-876c-2fc9c5f895da.png)

**Comment by carolinan** [comment]
Hi Nick!
Captions are already parts of theme.json  _elements_, does it not work for you?
https://github.com/WordPress/gutenberg/blob/trunk/schemas/json/theme.json#L1256

```
{
	"version": 2,
	"styles": {
		"elements": {
			"caption": {
				"color": {
					"text": "#111111"
				},
				"typography": {
					"fontSize": "0.8rem",
					"lineHeight": ".7",
					"textTransform": "uppercase"
				}
			}
		}
	}
}
```
You may also be interested in https://github.com/WordPress/gutenberg/pull/44094

**Comment by carolinan** [comment]
I am an idiot 😆 I mistook this for being in the Gutenberg repo, not TT3.

**Comment by bgardner** [comment]
Not sure the best path forward here, as image captions currently have center text align per this, in theme.css:

```
.wp-block-image figcaption {
    color: #555;
    font-size: 13px;
    text-align: center;
}
```

But theme.json does not support text align for captions (in elements), which means visual parody is not possible. (Unless I'm missing something.)

**Comment by ndiego** [comment]
Good call @bgardner. 

@mikachan I just realized what the main issue is. We are not opting into WP block styles, i.e. `add_theme_support( 'wp-block-styles' );` This is fine, but then you have to add them all yourself, which we are not doing. The issue arises with the Code block as well. It looks fine in the Editor, but the Frontend has no style. Enabling `add_theme_support( 'wp-block-styles' );` fixes this, as it does with the caption styles.

**Comment by mikachan** [comment]
Ahh I see, thanks for looking into this further. I've actually just opened an issue for something similar to this here: https://github.com/WordPress/gutenberg/issues/44510

I noticed that the block styles stylesheet is included in the editor, even when the theme doesn't opt into `wp-block-styles`. I'm wondering if this is correct, as it causes issues like this, where the styles are different between the editor and the front end. But I could be missing some context on why we need this stylesheet to always be used in the editor.

**Comment by carolinan** [comment]
@aristath and I discussed this earlier this week, but did not start working on a solution:
https://github.com/WordPress/twentytwentythree/issues/202#issuecomment-1257757088

**Comment by mikachan** [comment]
Ugh sorry @carolinan, I completely forgot about that issue and I haven't kept up with the conversation there. The comment you've linked to is particularly interesting, I'll let you know if I manage to take a longer look into this.

**Comment by ndiego** [comment]
I wonder if the inclusion of the theme.css file in the Editor when support for block styles is not added is simply a mistake or maybe there are backward compatibility reasons for non-block themes? 🤔

**Comment by mikachan** [comment]
https://github.com/WordPress/gutenberg/pull/44640 may fix this issue 🎉

**Comment by mikachan** [comment]
Fixed with https://github.com/WordPress/gutenberg/pull/44640 🙏
