### ISSUE TITLE
The space in the post meta is too large

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#238]
In the post meta, it looks like the theme is using both spaces inside the text blocks, and block spacing on the parent block:
<img width="1006" alt="Screen Shot 2022-10-03 at 12 34 24" src="https://user-images.githubusercontent.com/7422055/193558296-4a3325f3-a3e4-4cb3-9ae1-c8adb013dce1.png">

**Comment by mikachan** [comment]
Thanks! I've tried to fix this here: https://github.com/WordPress/twentytwentythree/pull/239
