### ISSUE TITLE
Lack of integration with bbPress

### ISSUE THREAD

**Issue by fernandotellado** [WordPress/twentytwentythree#245]
I've been testing the new theme with WP 6.1-beta2-54351 and forums pages showed a blank page, a common issue with Twenty-TwentyTwo theme

**Comment by mikachan** [comment]
I can replicate the problem you describe with Twenty Twenty-Three, Twenty Twenty-Two, and several other block themes. It looks like bbPress doesn't fully support block themes on its own. Have you seen this [plugin](https://en-gb.wordpress.org/plugins/bbp-style-pack/)? This may help, although I was unable to get it to work myself.

I don't think we should add anything to this theme to specifically support bbPress, but it would be good to know if including any other HTML templates would fix this issue, as it may help support other plugins too.

**Comment by fernandotellado** [comment]
I think that we should add bbPress support to every default theme, especially because bbPress is a long-term community project that should be preserved

**Comment by mikachan** [comment]
I've opened a ticket for bbPress: https://bbpress.trac.wordpress.org/ticket/3487#ticket

After looking into the compatibility issue with BuddyPress, it looks like bbPress may have a similar issue in that it's related to the index.php. However, the logic around this file seems more complicated in bbPress. I'll keep an eye on this ticket and see how it progresses 🤞

**Comment by fernandotellado** [comment]
Thanks a lot! :)

**Comment by mikachan** [comment]
I've submitted a patch for the above ticket here: https://github.com/bbpress/bbPress/pull/7

**Comment by fernandotellado** [comment]
Thanks @mikachan

**Comment by mikachan** [comment]
Closing as the theme has been merged into the WordPress Core SVN repository and is no longer maintained on GitHub.
