### ISSUE TITLE
Canary variation: improve buttons

### ISSUE THREAD

**Issue by mikachan** [WordPress/twentytwentythree#247]
- [ ] Default button and outline button are different sizes:

![image](https://user-images.githubusercontent.com/1645628/193879092-c11660f0-44bb-41db-b918-b7f76487eb8c.png)

- [ ] Buttons do not have a focus state

**Comment by manan18** [comment]
Please assign me this issue.

**Comment by yugalibalbudhe** [comment]
Hello there! I would like to contribute on this issue. Let me know apart from sizes of buttons and focus state is there anything else that you want to fix?

**Comment by manan18** [comment]
> Please assign me this issue.

Where do I find the buttons I need to Improve?

**Comment by yugalibalbudhe** [comment]
@mikachan can you please let me know in which files those buttons exists that we need to modify?

**Comment by audrasjb** [comment]
Hi there,
These buttons params are located in the [Canary style variation](https://github.com/WordPress/twentytwentythree/blob/trunk/styles/canary.json#L133).

**Comment by audrasjb** [comment]
See [Marigold style variation](https://github.com/WordPress/twentytwentythree/blob/trunk/styles/marigold.json#L277) for example.
