### ISSUE TITLE
Adminbar inherit styles from Block out style variation

### ISSUE THREAD

**Issue by audrasjb** [WordPress/twentytwentythree#248]
Just noted that the WP Adminbar inherits italics for the Block out style variation 😬 

<img width="1402" alt="Capture d’écran 2022-10-04 à 22 50 09" src="https://user-images.githubusercontent.com/1590998/193925434-8d3548f0-e771-4f5e-98c1-9c1328bbb286.png">

**Comment by carolinan** [comment]
Good catch! The link styles are affecting all links that are not button blocks, this is not limited to this theme.

```
a:where(:not(.wp-element-button)) {
    color: var(--wp--preset--color--contrast);
    font-family: var(--wp--preset--font-family--ibm-plex-mono);
    font-style: italic;
    font-weight: 400;
    text-decoration: underline;
}
```

I think that the easiest way to solve this would be to add a font-style to  `#wpadminbar *` in core?
What do you think?

**Comment by audrasjb** [comment]
Yep! Looks perfect to me 👍

**Comment by carolinan** [comment]
I will close this, new ticket was opened upstream https://core.trac.wordpress.org/ticket/56737
