### ISSUE TITLE
Block out variation: Site title in footer too large

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#251]
The site title in the Footer area is extremely large, and looks quite disproportionate in that area:

![Post_3_–_Twenty_Twenty-Three_Testing_and_Slack___comet___A8C](https://user-images.githubusercontent.com/7662449/194105347-1a359bc0-5742-401e-946f-a4faaa80c7ed.jpg)

Suggest making the Site title in the footer smaller, like it is in the other variations.

**Comment by carolinan** [comment]
I struggle with this size too, 
-it is not possible to have one size in the footer and one size in the header, or hide the footer title **using theme.json.**

**Comment by mikachan** [comment]
@critterverse @beafialho, it would be good to have your thoughts on this. There's not much we can do via theme.json here, as both the header and footer use the site title block. I'm wondering if we should reduce the maximum size for this font size, perhaps by around 50%? So it would still be very large in comparison with all the other font sizes, but would maybe look less impactful in the footer.

**Comment by beafialho** [comment]
I'm ok with reducing the max site title size by 50%.
