### ISSUE TITLE
Blog (Alternative) Template: Replace Author Bio with Paragraph block

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#252]
In testing the Blog (Alternative) Template, I noticed a "Post Author Biography" block at the top.

### Problem

This block, in this location, doesn't seem to fit well here, since a blog can have multiple authors, so whose bio would be displayed? (In addition, the Post Author Name block would need to accompany a bio block.)

![Cursor_and_Editor__beta__‹_Twenty_Twenty-Three_Testing_—_WordPress](https://user-images.githubusercontent.com/7662449/194129569-4358fd0e-4495-47ae-8ebf-4ec6041bb821.jpg)

When revisiting the original Figma design, it looks like the text above the posts isn't necessarily specifically meant to be an author bio:

![Twenty_Twenty_Three __Figma_Community](https://user-images.githubusercontent.com/7662449/194129820-19e9f917-6177-4674-90a2-331132f3d686.jpg)

### Solution

I would suggest changing the Post Author Biography block to a Paragraph block, which is more flexible, and avoids the issue of whose bio should be displayed when there are multiple post authors.

**Comment by carolinan** [comment]
WordPress 6.1 release is already in string freeze, so a new text can not be added. I don't think an empty paragraph would be helpful.
-The block could still be removed if that is agreed on.

**Comment by mikachan** [comment]
Thanks, @carolinan. So I guess our options are to stay with the author bio or remove the block entirely.

I think I'd rather keep the author bio, as I quite like content being there in this template. I understand this doesn't work well with multiple authors, but the user can edit or remove this block if it doesn't work for their use case.

@beafialho, what do you think?

**Comment by carolinan** [comment]
I think the majority of sites have neither multiple authors nor a user biography filled out.
This would be a good thing to document in the theme's about page on .org.

**Comment by beafialho** [comment]
I'm ok with removing this block entirely. In this case, the first separator - above the first post - should be removed.

**Comment by carolinan** [comment]
It is not possible to style the first post differently from the second and last etc using theme.json or the template, the same blocks are repeated inside the post template.

The top border is on the row:
<img width="1391" alt="Screen Shot 2022-10-06 at 12 56 53" src="https://user-images.githubusercontent.com/7422055/194295994-94e8f931-0ab6-41e0-ad5c-a4de48efca62.png">

It could be switched to a bottom border, but then there would be an orphaned line below the last post instead.

**Comment by beafialho** [comment]
> It is not possible to style the first post differently from the second and last etc using theme.json or the template, the same blocks are repeated inside the post template.
> It could be switched to a bottom border, but then there would be an orphaned line below the last post instead.

I'm aware of that. IMO a line below the last post would be preferred to a line above the first post.
