### ISSUE TITLE
Blog (Alternative) Template: Post title not legible if Query Loop block in grid view 

### ISSUE THREAD

**Issue by kathrynwp** [WordPress/twentytwentythree#254]
In testing the Blog (Alternative) Template, I found that switching the Query Loop display to grid makes the post titles unreadable.

### To replicate

1. Publish three posts
2. In Settings > Reading, set "Blog pages show at most" to any number greater than 3
3. Go to Appearance > Editor > Browse all Templates
4. Click the Blog (Alternative) template to open it
5. Select the Query Loop block
6. Select the "Grid View" option

### Result

The post titles are displayed too narrow to be read well

![Editor__beta__‹_Twenty_Twenty-Three_Testing_—_WordPress](https://user-images.githubusercontent.com/7662449/194135470-9e2a6e9f-57bc-402c-aa89-31bf903fbb22.jpg)

### Expected

Post titles should be readable

### Tested with

WordPress 6.1-beta3-54390
Gutenberg 14.2.0
Twenty Twenty-Three downloaded from GitHub approx. 3 hours ago

**Comment by carolinan** [comment]
I think this is fine since the grid is not the default setting. As a user, you would need to do more customizations to move the title.

**Comment by mikachan** [comment]
The easiest way to fix this is to change the orientation of the group within the post template, and it's just that the layout works best set to horizontal in the list view, and vertical as a grid. If the user has already used the editor to change the layout type, then I think it's fine to expect them to also adjust the orientation to suit.

I think we can close this, thanks both.
