### ISSUE TITLE
Subject Tag is missing

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentythree#276]
We have 9 different subject tags. https://make.wordpress.org/themes/handbook/review/required/theme-tags/ 

We can use max up to 3. Which subject tags are suitable for this theme?

**Comment by mikachan** [comment]
Good idea! Hmm, this is tricky as TT3 is a minimal theme. What about `blog`, `portfolio`, and `news`? Or maybe just `blog` and `portfolio`?

@beafialho, which tags do you think we should use from the [available options](https://make.wordpress.org/themes/handbook/review/required/theme-tags/#subject-tags-max-3-tags)?

**Comment by beafialho** [comment]
Yes, I think `blog`, `portfolio` and `news` work well!
