### ISSUE TITLE
Add code linting with required GitHub workflows

### ISSUE THREAD

**Issue by thelovekesh** [WordPress/twentytwentythree#28]
Add code linting to make sure WordPress Coding Standards are maintained during the development.

Tasks:

- [x]  Add Stylelint for CSS linting.
- [x]  Add PHPCS for PHP CS and linting.
- [x]  Add required GitHub workflows to run linting on PRs.

Need Discussion:
- Add `pre-commit` hook
- Is config for JS linting required?

**Comment by colorful-tones** [comment]
I'm not a fan of `pre-commit` hooks. I used to be, but fine with CI flagging.
