### ISSUE TITLE
XX-Large font size is BIG

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentythree#282]
After ~four characters, the `xx-large` font size starts breaking down (on desktop). 

I appreciate that we want to show of fluid type, but I think its too much. 

What if we set the max to `10rem` instead of `20rem`? May still be too big even. 

### Current
<img width="1549" alt="CleanShot 2022-10-13 at 16 15 33@2x" src="https://user-images.githubusercontent.com/1813435/195700725-f356f033-176e-4746-9a5b-cf5d8c8098c6.png">

### Proposal
<img width="1546" alt="CleanShot 2022-10-13 at 16 16 19@2x" src="https://user-images.githubusercontent.com/1813435/195701016-7e4ccf59-1077-46fd-9973-a59dc58411e0.png">

**Comment by mikachan** [comment]
> What if we set the max to 10rem instead of 20rem?

This looks fine to me. We originally used the `20rem` size to cater for the very large 404 title, but we're no longer using this, so I think reducing this size is a good idea. @beafialho, is this OK with you?

**Comment by beafialho** [comment]
Thank you for the suggestion @richtabor. I completely agree it looks too big, `10 rem` looks much better.
