### ISSUE TITLE
Block out variation: White Page Titles

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentythree#283]
Are the white page titles intentional for the `Block out` variation?

<img width="1540" alt="CleanShot 2022-10-13 at 16 23 10@2x" src="https://user-images.githubusercontent.com/1813435/195703503-066cec4a-3424-439f-969b-7552205c8658.png">

**Comment by mikachan** [comment]
Yes, this is intentional. Here's a screenshot of the Figma file:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/1645628/195890378-d8991f18-96b7-49e6-9188-07d27835af0a.png">
