### ISSUE TITLE
Update button styles for `is-style-outline` in Pilgrimage variation

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentythree#292]
When using the `Pilgrimage` style variation and buttons with the default `is-style-outline` class, they don't look good with the default gradient:

![image](https://user-images.githubusercontent.com/7585600/197266048-eb03a31c-9962-4ed7-84e9-263f036a25f4.png)

**Comment by mikachan** [comment]
Thanks! I don't think the default gradient should be applied to 'outline' buttons at all, otherwise, they're not really an outline button. I have a potential fix here: https://github.com/WordPress/gutenberg/pull/45234

**Comment by mikachan** [comment]
This should be fixed by https://github.com/WordPress/gutenberg/pull/45234 🤞
