### ISSUE TITLE
Does spacingScale steps 0 in theme.json do anything?

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#293]
I am wondering if setting the spacingScale to 0 steps actually does anything?
The "spacingSizes" replaces the default sizes in the control either way.  I mean, the default doesn't need to be disabled because it is being overwritten?
```
"spacingScale": {
		"steps": 0
	},
```

**Comment by mikachan** [comment]
I think all it's currently doing is preventing one additional step from being generated. If I remove it, I see this additional preset: `--wp--preset--spacing--20: 0.44rem`.

I think we originally added the 0 steps to prevent multiple other steps from being generated that didn't really fit in with the custom sizes. However, now that it's only this single smaller size, I don't think it's as important. It's perhaps an improvement to include a smaller spacing preset.

I imagine that the 0 steps setting may look quite confusing to new users as well.

**Comment by carolinan** [comment]
I am seeing a different result.
The default preset variables are always printed, (just like default colors, gradients).
Some of the values in the presets are replaced with the theme sizes, since the same slugs are used.
But the default presets are not in the **control**, the items in the control are from the custom sizes, not the default.

**Comment by carolinan** [comment]
Either way, it also doesn't seem to do any harm.

**Comment by mikachan** [comment]
I'm also only seeing the custom sizes in the control. It looks like there's a maximum of 6 allowed in the control, maybe this is why only the custom sizes are shown, as there are 6 of them?

Yes, it doesn't seem to do any harm either way! Do you think it's best to remove it?

**Comment by mikachan** [comment]
Closing as the theme has been merged into the WordPress Core SVN repository and is no longer maintained on GitHub.
