### ISSUE TITLE
Track Related Gutenberg Issues

### ISSUE THREAD

**Issue by mikachan** [WordPress/twentytwentythree#30]
This issue is to list and track any Gutenberg issues that would benefit Twenty Twenty-Three and its variations.

Required for base theme (WP 6.1):

- [x] https://github.com/WordPress/gutenberg/issues/41142
- [x] https://github.com/WordPress/gutenberg/pull/42847
- [x] https://github.com/WordPress/gutenberg/pull/40085
- [x] https://github.com/WordPress/gutenberg/pull/43088
- [x] https://github.com/WordPress/gutenberg/pull/42594
- [x] https://github.com/WordPress/gutenberg/pull/43466
- [x] https://github.com/WordPress/gutenberg/pull/43925
- [x] https://github.com/WordPress/gutenberg/pull/44144
- [x] https://github.com/WordPress/gutenberg/issues/44262

NOT required, but nice to have for style variations:

- [x] https://github.com/WordPress/gutenberg/issues/43676
- [ ] https://github.com/WordPress/gutenberg/issues/43660
- [ ] https://github.com/WordPress/gutenberg/issues/42794 (allow variations to style 'outline' buttons)
- [ ] https://github.com/WordPress/gutenberg/issues/40699
- [ ] https://github.com/WordPress/gutenberg/issues/43395
- [ ] https://github.com/WordPress/gutenberg/issues/43405
- [ ] https://github.com/WordPress/gutenberg/issues/42105 (allow variations to use gradient backgrounds)
- [x] https://github.com/WordPress/gutenberg/pull/41972
- [x] https://github.com/WordPress/gutenberg/issues/43523
- [ ] https://github.com/WordPress/gutenberg/issues/43347
- [ ] https://github.com/WordPress/gutenberg/issues/36122
- [ ] https://github.com/WordPress/gutenberg/issues/43816
- [ ] https://github.com/WordPress/gutenberg/issues/43627
- [ ] https://github.com/WordPress/gutenberg/issues/44428
- [ ] https://github.com/WordPress/gutenberg/issues/27809

**Comment by jasmussen** [comment]
Post Featured Image looks close, and I'll take a quick look at image block placeholders to see if there's a small tweak we can do.

**Comment by carolinan** [comment]
I saw that there was a style variation with a gradient background submitted, so we need this issue to be solved, or gradients can't be replaced:
https://github.com/WordPress/gutenberg/issues/42105

**Comment by carolinan** [comment]
Perhaps this one? In the design, the placeholder title only says "Blog posts"
Add a setting to hide the prefix in the archive title: https://github.com/WordPress/gutenberg/pull/42594

_Update: Merged_

**Comment by carolinan** [comment]
- [ ] Open a Gutenberg issue and PR to add border support to query pagination (and inner blocks). Remember to add the new issue to the border tracking issue.

**Comment by beafialho** [comment]
I think [this issue](https://github.com/WordPress/gutenberg/issues/43523) is a nice to have.

**Comment by jasmussen** [comment]
[An FYI for the misplaced close icon in navigation](https://github.com/WordPress/gutenberg/issues/43523#issuecomment-1225610001), I think we can do it but the theme needs some small changes too.

**Comment by mikachan** [comment]
Thanks so much for the update, @jasmussen! That sounds great.

**Comment by luminuu** [comment]
Two things I noticed while creating designs for TT3:

Post Featured Image block: Enable gradient overlay: https://github.com/WordPress/gutenberg/issues/43676
Separator Block: background color defined in theme.json is not applied correctly: https://github.com/WordPress/gutenberg/issues/43660

**Comment by matiasbenedetto** [comment]
https://github.com/WordPress/gutenberg/pull/44126 is an experiment around Styling blocks inside template parts with theme.json: https://github.com/WordPress/gutenberg/issues/43347
