### ISSUE TITLE
Variation "Maresa"

### ISSUE THREAD

**Issue by colinchadwick** [WordPress/twentytwentythree#34]
This is my contribution to the TT3 style variations:

Screenshot:
![TT3 Variation _Maresa_](https://user-images.githubusercontent.com/62803839/184106684-0532dd33-df5c-49a4-96fb-b295bbd8bdbb.png)

Figma link:
https://www.figma.com/file/NV8HsXUVEmTZNCrCOZdJcd/TT3-Variation-%22Maresa%22?node-id=0%3A1

JSON:
[variation-maresa.json.zip](https://github.com/WordPress/twentytwentythree/files/9307684/variation-maresa.json.zip)

As this is the first time I'm working with style variations, please let me know if I'm missing something.

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
