### ISSUE TITLE
Links Details

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentythree#4]
- [x] Can we keep the `#345C00` color to the links in paragraphs only?

<img width="743" alt="Captura de ecrã 2022-08-10, às 16 51 33" src="https://user-images.githubusercontent.com/65220155/183954204-f251e059-8afd-4597-8913-1308d0d2a03f.png">

- [ ] Also, let's match the links with TT2: `1px` underline thickness and a `text-underline-offset:.25ch` with the same hover effect.

https://user-images.githubusercontent.com/65220155/183954780-6abbeca1-c8c9-4f55-b00b-a5d69d8e2e41.mp4

**Comment by carolinan** [comment]
Was this change implemented? I noticed that the archive block has green links on the front and not in the editor.

**Comment by mikachan** [comment]
> I noticed that the archive block has green links on the front and not in the editor.

I've just noticed that the default link color was using the wrong variable name! Here's a fix: https://github.com/WordPress/twentytwentythree/pull/80

I don't think the underline thickness has been addressed yet. We'd need to do this with CSS.

**Comment by carolinan** [comment]
Should the secondary color be used on links in the paragraph block only? It is on all links in the post content block.

**Comment by mikachan** [comment]
I think the reason the color is set on the post content block is so that links like those in the footer, which are in paragraphs, are not included in the color change.

**Comment by beafialho** [comment]
@mikachan I'd love it if we could improve the appearance of link underlines. The link underlines in the TT3 base theme are currently too thick and close to the word.

- Let's apply `text-underline-offset: .15em` to all links.
- Let's make the underlines thinner as in [this site](https://andersnoren.se/themes/bjork/blog/)

**Comment by mikachan** [comment]
In order to apply the underline offset we'd need to use CSS. I was trying to avoid using any CSS for this theme, to show what's currently possible with Global Styles and theme.json. It also means we don't need to include a functions.php file, as we'd need this to enqueue the stylesheet. Including this file doesn't have any negative impacts from a technical perspective, but I believe not including it allows this theme to be a good example of what can be achieved without this file.

We can change the underline thickness to 1px via theme.json, although without the offset I'm not sure it has the same effect:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/1645628/194302708-2ddd310e-472b-42af-ae6d-86d006e6a5f8.png">

**Comment by beafialho** [comment]
> In order to apply the underline offset we'd need to use CSS. I was trying to avoid using any CSS for this theme, to show what's currently possible with Global Styles and theme.json

Don't some variations have custom link underlines, hover effects, etc? If they do, I don't see the point in not doing that in the base theme as well. It would still have minimal CSS.

> We can change the underline thickness to 1px via theme.json, although without the offset I'm not sure it has the same effect:

That alone could already improve its overall appearance.

**Comment by mikachan** [comment]
> Don't some variations have custom link underlines, hover effects, etc? If they do, I don't see the point in not doing that in the base theme as well. It would still have minimal CSS.

Some of the variations do customise the link pseudo-states, however, we're not using CSS to do it, they're all done via the variations JSON files. The property `text-underline-offset` cannot currently be set via theme.json.

> That alone could already improve its overall appearance.

OK! I'll open a PR for this.

**Comment by beafialho** [comment]
I see. Let's see if only the underline thickness improves the link appearance then.
