### ISSUE TITLE
Archive template: match the Figma

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentythree#44]
Currently the archive template is a query block with a list style view. It should match the Figma design instead, using a 2 x 3 layout:

<img width="1200" alt="archive" src="https://user-images.githubusercontent.com/5375500/184420644-fa2ef459-ad49-45df-ab8f-42e44824a8ea.png">

**Comment by mikachan** [comment]
This was addressed by https://github.com/WordPress/twentytwentythree/pull/47.
