### ISSUE TITLE
Single + Page templates: match Figma

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentythree#45]
There are a few details from the Figma that should be refined in the templates:

**Page & Single**
- [ ] The Post Featured Image should come before the Post Title
- [ ] There should not be a separator between the Post Title and the Post Content 

**Single**
- [ ] The post meta should be split into a row and wide aligned, with the Post Date, Category and Author on the left, and the Tags on the right. 

Figma reference [here](https://www.figma.com/file/j469TEkvf2YJ3EVQm9X4Nt/TT3?node-id=147%3A1719)

**Comment by kishanjasani** [comment]
@mikachan I am not able to access the Figma file.

**Comment by mikachan** [comment]
Hi @kishanjasani. I don't believe the Figma file has any access restrictions. Are you able to access this link: https://www.figma.com/community/file/1139275543113752375 ?

**Comment by kishanjasani** [comment]
@mikachan Now I can access the files.
