### ISSUE TITLE
Variation "Pastel"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#48]
Screenshot:
![Screenshot 2022-08-15 at 12 35 34](https://user-images.githubusercontent.com/20610429/184620766-e02e222a-5247-42cb-80b2-5d3cc8fc07e4.png)

Figma Link: 
https://www.figma.com/file/CHvE6JTndoOlNMN76JjRUT/TT3-Variation-%22Pastel%22?node-id=2%3A9

JSON: 
[variation-pastel.json.zip](https://github.com/WordPress/twentytwentythree/files/9336669/variation-pastel.json.zip)

Not sure if we are able to change a bit header and footer backgrounds or do we need to stick to the default Figma file as it is and play just with the colors and fonts? Can we submit more than one variation :)?

**Comment by mikachan** [comment]
> Not sure if we are able to change a bit header and footer backgrounds or do we need to stick to the default Figma file as it is and play just with the colors and fonts? 

The general idea is to use the style variation JSON file to customize as much as you'd like.

> Can we submit more than one variation :)?

Yes!

**Comment by anarieldesign** [comment]
Aha great, I thought we need to stick as much possible to the original figma files and not to get soo wild 😅. Good to know. I'll try to explore and do more customizations in theme.json file. If those 2 that I submitted so far are too simple just delete them and I'll do something more soon 😅. I wasn't sure how "crazy" can I go with the theme.json 🤣

**Comment by anarieldesign** [comment]
> > Not sure if we are able to change a bit header and footer backgrounds or do we need to stick to the default Figma file as it is and play just with the colors and fonts?
> 
> The general idea is to use the style variation JSON file to customize as much as you'd like.
> 
> > Can we submit more than one variation :)?
> 
> Yes!

Aha great, I thought we need to stick as much possible to the original figma files and not to get soo wild 😅. Good to know. I'll try to explore and do more customizations in theme.json file. If those 2 that I submitted so far are too simple just delete them and I'll do something more soon 😅. I wasn't sure how "crazy" can I go with the theme.json 🤣. Can we create different home page layout from the default one in Figma files or that we stick with the same layout and content? Sorry for soo many questions, just want to be sure what we are all allowed to do here 😅

**Comment by mikachan** [comment]
>  If those 2 that I submitted so far are too simple just delete them and I'll do something more soon

Whether you want to submit them is entirely up to you - I personally don't think simplicity is a problem, and you're very welcome to experiment more with your existing submissions or create some more.

> Can we create different home page layout from the default one in Figma files or that we stick with the same layout and content?

As you can't influence the home page content from the JSON file itself, I'd say you can't specifically change this. However, you can influence spacing and content width from the JSON file, and many specific block settings. There's a variation submission here that overrides a variety of specific block settings: https://github.com/WordPress/twentytwentythree/pull/40

I've just realised you many have meant the content just in the Figma files, as part of your design. @beafialho, what are your thoughts on using different content here?

**Comment by anarieldesign** [comment]
No problem @mikachan, all clear now 💪. I'll submit new one soon, with different customization and styles. Now I have a better idea what we are allowed to do 🙏. Thank u ❤

**Comment by anarieldesign** [comment]
And we can leave this one too as I can submit more of them 👌🙏

**Comment by mikachan** [comment]
You're very welcome, looking forward to seeing another variation from you!

**Comment by anarieldesign** [comment]
Thank u and sorry for soo many questions 😅🙏

**Comment by beafialho** [comment]
> Not sure if we are able to change a bit header and footer backgrounds or do we need to stick to the default Figma file as it is and play just with the colors and fonts?

> I've just realised you many have meant the content just in the Figma files, as part of your design. @beafialho, what are your thoughts on using different content here?

Yes, you can definitely play with header and footer. For example reducing the spacing around the items or making nav items be lowercase 🙂

**Comment by carolinan** [comment]
I tried changing the template part background color using theme.json, but it doesn't work because the block does not have color support. (When we build, the color settings are on the inner blocks)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
