### ISSUE TITLE
Variation "Salmon"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#49]
Screenshot:
![Screenshot 2022-08-15 at 13 05 15](https://user-images.githubusercontent.com/20610429/184624540-f52c61ba-1b46-491a-8560-e53290dd79f5.png)

Figma File:
https://www.figma.com/file/4ww4vOJJD38ozSZyd8UUfF/TT3-Variation-%22Salmon%22?node-id=2%3A9

JSON:
[variation-salmon.json.zip](https://github.com/WordPress/twentytwentythree/files/9336805/variation-salmon.json.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
