### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by kraftbj** [WordPress/twentytwentythree#5]
Opening up an issue to track the creation of a demo site. I've handled the paperwork of getting a *.wordpress.net site for the past few years and happy to continue if desired.

I'd get the site setup, keep it up to date with Core/Gutenberg/plugins/TT3 code. A themer would go in to actually setup the demo site as desired.

**Comment by mikachan** [comment]
That would be brilliant if you could handle this, thanks @kraftbj!

**Comment by kraftbj** [comment]
@mikachan Besides you, will anyone else need access to build out the demo?

**Comment by mikachan** [comment]
Please can you add @beafialho as well?

**Comment by kraftbj** [comment]
I've added both of y'all. I'm doing some additional tweaks to ensure the theme is kept up to date (e.g. within 5 minutes of a PR's merging), but feel free to start setting it up. You should have e-mails, but if not and not in spam, let me know!

**Comment by mikachan** [comment]
Can confirm I got an email and I'm successfully logged in. Thanks so much for setting this up!

**Comment by beafialho** [comment]
Thank you for handling this and adding me as well. I'm successfully logged in!
