### ISSUE TITLE
Variation "Dusk"

### ISSUE THREAD

**Issue by colinchadwick** [WordPress/twentytwentythree#50]
And another one:

Screenshot:
![TT3 Variation _Dusk_ (1)](https://user-images.githubusercontent.com/62803839/184668587-328968c7-2f01-4dde-aeaf-dfda3ade5d7c.png)

Figma link:
https://www.figma.com/file/Fft6s8KS3I0BUcwu4ybdLd/TT3-Variation-%22Dusk%22?node-id=2%3A9

JSON:
[variation-dusk.json.zip](https://github.com/WordPress/twentytwentythree/files/9338287/variation-dusk.json.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
