### ISSUE TITLE
"No separators" templates

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#58]
Should the single-no-separators.html remain in the theme, but without the separator above the post meta?

The page does not have separators, I suggest removing the template.

**Comment by mikachan** [comment]
Good spot, I think we should remove the template.

**Comment by carolinan** [comment]
I removed it in #55

**Comment by mikachan** [comment]
Thank you!

I don't think we need the single-no-separators.html template either. @beafialho, do you think we should have a single post template without the separator above the post meta, or should we just remove this 'no separator' template? It was carried over from TT2.

**Comment by beafialho** [comment]
Hmm, I think we should remove the **Page (No Separators)** and **Single Post (No Separators)** templates from the theme and just have Single Post and Page look like the mockups.

Single Post template should only have a separator before the post meta:

| with Featured Image      | without Featured Image |
| ----------- | ----------- |
|   ![Single Post](https://user-images.githubusercontent.com/65220155/185155568-17c5a6ef-3552-4bcc-8e6b-62f84581041b.png)  |   ![Single Post (without Featured Image)](https://user-images.githubusercontent.com/65220155/185155510-032816c5-3269-48b3-9bc6-41c760629a36.png)   |

Page template should not have separators at all neither it should have a comments section:

| with Featured Image      | without Featured Image |
| ----------- | ----------- |
|  ![Page](https://user-images.githubusercontent.com/65220155/185156528-ccf40f49-d520-4026-b209-a9f1862b0ca4.png)  |   ![Page-1](https://user-images.githubusercontent.com/65220155/185156570-89600dba-0df6-4f5a-99ab-cfacff7d4684.png) |

**Comment by mikachan** [comment]
That sounds great to me, thanks for confirming!
