### ISSUE TITLE
Variation "Mint"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#60]
Screenshot:
![Screenshot 2022-08-16 at 10 10 22](https://user-images.githubusercontent.com/20610429/184830864-1281ea27-250d-4436-8762-82944f916546.png)

Figma:
https://www.figma.com/file/CqspxoBojdP0say5PdNcYU/TT3-Variation-%22Pastel%22?node-id=0%3A1

JSON:
[variation-mint.json.zip](https://github.com/WordPress/twentytwentythree/files/9348938/variation-mint.json.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
