### ISSUE TITLE
Update the font sizes and spacing on the 404 page.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#62]
The 404 page pattern needs to be updated to match [the design](https://www.figma.com/file/ohYEHkZzGjOse46NceTfj5/Twenty-Twenty-Three?node-id=301%3A522).

**Comment by tanvirulhaque** [comment]
I have added a PR with the update on this. 

https://github.com/WordPress/twentytwentythree/pull/63
