### ISSUE TITLE
Variation "Sea"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#64]
Screenshot:
![Screenshot 2022-08-16 at 11 27 45](https://user-images.githubusercontent.com/20610429/184846363-c0d76c08-1b44-4848-a917-8ee65e0f0b1e.png)

Figma:
https://www.figma.com/file/4Westbc4Hp3NIiWlRsXOzY/TT3-Variation-%22Sea%22?node-id=409%3A214

JSON:
[variation-sea.json.zip](https://github.com/WordPress/twentytwentythree/files/9349436/variation-sea.json.zip)

**Comment by samxmunoz** [comment]
Oh this is my favorite you submitted @anarieldesign!!

**Comment by MaggieCabrera** [comment]
That gradient is gorgeous, so nice to see variations making use of that

**Comment by anarieldesign** [comment]
Thank you soo much, soo happy u like this one :)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
