### ISSUE TITLE
Variation "Funky"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#71]
Screenshot:
![Screenshot 2022-08-17 at 13 05 34](https://user-images.githubusercontent.com/20610429/185103676-18e85ba0-e272-481a-8360-7de47dd5627c.png)

Figma:
https://www.figma.com/file/2CPz5M7rq4pX1o5Gx3urQA/TT3-Variation-%22Funky%22?node-id=2%3A9

JSON:
[variation-funky.json.zip](https://github.com/WordPress/twentytwentythree/files/9359018/variation-funky.json.zip)

**Comment by critterverse** [comment]
Love this button gradient! 😍

**Comment by anarieldesign** [comment]
> Love this button gradient! 😍

Thank you, I was playing a bit :)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
