### ISSUE TITLE
Variation "Bantam"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#72]
Screenshot:
![Screenshot 2022-08-17 at 13 08 56](https://user-images.githubusercontent.com/20610429/185104340-f1124954-4a7d-4e9f-a526-45de5b450e92.png)

Figma: 
https://www.figma.com/file/X9roJpG5KECqJLpdYYXL2e/TT3-Variation-%22Bantam%22?node-id=409%3A214

JSON:
[variation-bantam.json.zip](https://github.com/WordPress/twentytwentythree/files/9359038/variation-bantam.json.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
