### ISSUE TITLE
Child theme with style variations spin-off

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/twentytwentythree#73]
Proposal for consideration:

- TT3 theme - with 2-4 style variations, and
- TT3 child theme - with a handful of community-contributed style variations

Possible **benefits**:

- Test the limits of current WordPress theme APIs
- Encourage further creative expression by encouraging more fonts and even Patterns included

Possible **drawbacks**:

- Harder to onboard new contributors with two different repos/projects
- Maintenance - related to above. Two projects to maintain.
- Possible that the TT3 child theme may be underutilized (low install numbers) and impact morale of contributors.
- Shift in timeline and progress, but this could potentially be a benefit too: faster ship times with separation of concerns.

Just opening this up to discussion and consideration. Thanks!

**Comment by colorful-tones** [comment]
FWIW - I would be happy to host weekly triage sessions in Make Slack and coordinate cross-repo communication for this endeavor. Even if we do not go with this proposal, I would be glad to offer to do so for the project's current iteration.

**Comment by pbking** [comment]
I see child themes of TT3 as a potentially very helpful thing.  I'm keeping that in mind as much or more than variations as I tinker. 

I'm not sure about changing the direction of TT3's release/timeline/goals.  However I really like the idea of a child theme that's even MORE focused on community variations.

I would love to see a dozen (or more) variations ship with TT3 (though I think that's unlikely) and that could really demonstrate how far it can stretch.  

And to follow up with a child theme (released on a different timeline, but developed in the same way) that's even MORE focused on community involvement (and with more options and perhaps a better integrated workflow) sounds great.

I'm really keen to make building variations the "Gateway to Theme Dev".

**Comment by mikachan** [comment]
Thanks for starting this discussion!

I particularly like the idea of continuing to create style variations beyond those that are bundled with TT3. I think this is a great opportunity to introduce people to block themes and building variations, just as @pbking said above, with the help of the community and experienced block-themers. It also provides a space to test Gutenberg PRs, in a similar way to how `emptytheme` is currently used, but with more opinionated settings enabled.

I'm not sure about this being part of the current TT3 project, and in my opinion, it would be best to start this initiative soon after TT3 has launched. This would also tackle a few of the drawbacks mentioned:

- This repo would close as TT3 is merged into Core, and we could open another repo specifically for this project
- If we began this work after the TT3 launch, it would not impact the current timeline

I'd love to hear more thoughts on this.

**Comment by MaggieCabrera** [comment]
I'm very interested in the possibility of launching more community built block themes besides the yearly default theme, and I'd be very happy to explore the possibility. Building child themes could be an idea for sure.

**Comment by colorful-tones** [comment]
> This repo would close as TT3 is merged into Core, and we could open another repo specifically for this project
> If we began this work after the TT3 launch, it would not impact the current timeline

Great idea! I like it. 👍

**Comment by colorful-tones** [comment]
I'll leave this open a few days for any further feedback, but then likely close it out. 👍

**Comment by carolinan** [comment]
The problem with adding child themes to the theme directory is that it removes the option of creating a child theme of that theme, which makes it more difficult for the end user to make changes.

**Comment by colorful-tones** [comment]
@carolinan that is something I had not known or considered, and does seem like a bit of a dilemma. However, style variations and Global Styles seems to offer a nice compromise. If we create a child theme with several style variations then it’s intent and feature offering is wholly new, and users could even change any of the variations with Global Styles.

So, perhaps the child theme could have “experimental” in the description. Although, I feel like that may be unnecessary and would discourage usage. 🤔

**Comment by colorful-tones** [comment]
Thanks for the great discussion around this. I'm closing it out.
