### ISSUE TITLE
Variation "Rough Draft"

### ISSUE THREAD

**Issue by justintadlock** [WordPress/twentytwentythree#86]
**Update:** 

- JSON file is here: https://github.com/justintadlock/tt3-rough-draft/blob/master/theme.json
- Raw: https://raw.githubusercontent.com/justintadlock/tt3-rough-draft/master/theme.json

~~Like its title, this variation is still very much a _rough draft_.  However, I wanted to go ahead and share progress in case others were looking at how to override certain things (there's quite a bit of experimentation in there).~~

~~It took me a bit to learn some of the newer stuff.  I haven't tackled fluid typography yet, but it's coming.  I also need to look into mapping some custom slugs to TT3's existing slugs for things like font sizes.~~

~~Current progress is saved as a child theme in this repo (easy to install and test this way): https://github.com/justintadlock/tt3-rough-draft~~

## Screenshot 

The following is a screenshot of a single post (no separators template) with various blocks:

![tt3-variation-006](https://user-images.githubusercontent.com/1816309/185696067-d6930872-c596-4060-bf58-d449a2611d3b.jpg)

**Comment by justintadlock** [comment]
If I'm being honest, I could spend another week or two tweaking this and tinkering with different ideas.  My primary goal with this variation was to see how flexible style variations could be outside of just changing a few colors in a palette and selecting a couple of fonts.  So, there's very much a lot of experimentation.  It's been a ton of fun.  Plus, I managed to get some bugs reported upstream, so that's always good.

The JSON file is here: https://github.com/justintadlock/tt3-rough-draft/blob/master/theme.json (assuming we'd actually name that `rough-draft.json`).

The following are a few screenshots of the theme:

## Homepage

![rough-draft-home-001](https://user-images.githubusercontent.com/1816309/187759480-2281f948-216c-4b40-86f1-accf12b11cbc.jpg)

## Single post with various blocks

![rough-draft-single-post-001](https://user-images.githubusercontent.com/1816309/187759494-1b1fe0de-a821-43a8-a3de-78c05a6e8bf6.jpg)

## Post comments section

![rough-draft-comments-001](https://user-images.githubusercontent.com/1816309/187759506-e3e46458-e372-4964-9598-3ca78dfa6179.jpg)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
