### ISSUE TITLE
"Footer" is not an existing pattern category

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentythree#87]
The default footer pattern uses a category called "footer", but this category is not registered.

**Comment by carolinan** [comment]
I asked around to see if there are plans to add this as a new category in 6.1 but haven't found anything out yet.

**Comment by mikachan** [comment]
Thank you for looking into this. I think it would be nice if 'footer' was added to Core, as 'header' already exists as a category.

In the meantime, what do you think would be the best thing to do? If we use an existing category, maybe we could use 'featured' or 'text'? I guess I'm not particularly keen on 'featured' as there's nothing special about the footer itself. Or maybe it doesn't need a category?

Here's a list of the current block pattern categories for easy reference in this issue (from [here](https://core.trac.wordpress.org/browser/tags/6.0.1/src/wp-includes/block-patterns.php#L39)):

- buttons
- columns
- featured
- gallery
- header
- text
- query

**Comment by pbking** [comment]
IMO footer should be the category footers go in.  If it isn't added in 6.1 (I hope it is) then I think TT3 should register the category.

**Comment by carolinan** [comment]
I opened a new issue for it. This is a very small change if anyone wants a good first core issue.
https://core.trac.wordpress.org/ticket/56416

**Comment by carolinan** [comment]
The category has been added to core, so this can be closed.
