### ISSUE TITLE
 Undefined index: button while creating a new page 

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentythree#89]
`Notice</b>:  Undefined index: button in <b>C:\laragon\www\tt3\wp-includes\class-wp-theme-json.php</b> on line <b>1482`

Go to pages > add new and you will see the list of notice.

Make sure debug mode is enabled from wp-config.php file.

**Comment by carolinan** [comment]
This will keep appearing until the new _elements_ features are added to WordPress core.
