### ISSUE TITLE
Style variation thumbnails: Not displaying fonts used

### ISSUE THREAD

**Issue by critterverse** [WordPress/twentytwentythree#9]
The style variation thumbnail previews don't currently reflect the fonts used in each variation. The smaller Aa Aa preview that appears on hover looks correct, but the larger text on hover and the Aa text in the main preview are not displaying properly:

![variation-thumbnails](https://user-images.githubusercontent.com/77359364/183973454-83398060-25d0-47c6-ab91-9b71f6f08354.jpg)

**Comment by bgardner** [comment]
@critterverse Do you have Gutenberg active? I have experienced this same thing, but only with WP core. When I activate Gutenberg, this is resolved.

**Comment by mikachan** [comment]
It looks like this has been fixed, as I can see the fonts here now (I couldn't before!)

<img width="273" alt="image" src="https://user-images.githubusercontent.com/1645628/185373091-e939613e-8b18-406a-a008-a3ab1ead6a11.png">

I'm guessing there must have been a fix upstream in GB. If we notice it again we can just open this issue again.
