### ISSUE TITLE
Variation "Lolipop"

### ISSUE THREAD

**Issue by anarieldesign** [WordPress/twentytwentythree#90]
Screenshot:
<img width="568" alt="Screenshot 2022-08-22 at 15 27 24" src="https://user-images.githubusercontent.com/20610429/185934353-ea5e1a49-b1c1-41bf-9de3-ab4b13cf3da2.png">

Figma:
https://www.figma.com/file/525rrh1C6wK7LsYJotXve6/TT3-Variation-%22Lolipop%22-(Copy)?node-id=2%3A9

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
