### ISSUE TITLE
Button states: outline button should have dark background on hover

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/twentytwentythree#96]
Following button states should match with [figma](https://www.figma.com/community/file/1139275543113752375).

**Current:**

Hover: (outline button background)
<img width="534" alt="image" src="https://user-images.githubusercontent.com/1935113/186072675-e1295552-3a93-42f1-b439-19418ac63810.png">

Focus: (dashed outline for both buttons)
<img width="534" alt="image" src="https://user-images.githubusercontent.com/1935113/186072785-c0960833-0c25-4dfb-83ed-df8b39de7837.png">

**Expected:**
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/1935113/186068269-f2c74d41-263d-4de0-b104-099b94cbff96.png">

**Comment by carolinan** [comment]
There is no way to target the outline style variation using theme.json.

**Comment by mikachan** [comment]
> There is no way to target the outline style variation using theme.json.

Yeah... we'd need to use CSS. I may create a label for these kinds of issues, so we can decide on how much CSS we want to add (if any).

Is there a Gutenberg issue for styling outline buttons via theme.json? Maybe this one? https://github.com/WordPress/gutenberg/issues/42794

**Comment by MaggieCabrera** [comment]
I made a PR for this: https://github.com/WordPress/gutenberg/pull/43526

**Comment by mikachan** [comment]
Thanks @MaggieCabrera! It's actually the outline button variation we need to style with the above, but allowing CSS outlines to be controlled via theme.json is a great addition for style variation submissions.

**Comment by MaggieCabrera** [comment]
> Thanks @MaggieCabrera! It's actually the outline button variation we need to style with the above, but allowing CSS outlines to be controlled via theme.json is a great addition for style variation submissions.

ugh, goes to show what happens when you read GH issues too early in the morning! I still think my PR is a good one to have. The outline variations one is a much harder one and I don't think we can make that one on time given the work that needs to be done to block styles variations, sadly

**Comment by carolinan** [comment]
Once there is a UI for borders for buttons, I think the outline style should be removed from core, because the settings will make the block more flexible.

**Comment by MaggieCabrera** [comment]
> Once there is a UI for borders for buttons, I think the outline style should be removed form core, because the settings will make the block more flexible.

That will work for this specific variation but not for others (think of maybe the dotted separator?) so there's value on being able to control these via theme.json. I'm also keen on having the ability to select a variation as default that is not the current default one.

**Comment by carolinan** [comment]
Yeah, selecting a different default used to be possible with the ui, but it was removed.

**Comment by mikachan** [comment]
Closing this, as unfortunately, it's not currently possible to style outline buttons using theme.json.
