### ISSUE TITLE
Variation "Gray"

### ISSUE THREAD

**Issue by elbsegler63** [WordPress/twentytwentythree#97]
[Guide.pdf](https://github.com/WordPress/twentytwentythree/files/9400387/Guide.pdf)

![Style](https://user-images.githubusercontent.com/85250773/186100741-b61b7119-fd7f-4ae5-bf04-06400a14d191.PNG)
![Save Website as Image-2022-08-24_07-26-26 Stil Variation TT3 – Testen und Üben](https://user-images.githubusercontent.com/85250773/186100758-a5a044e2-c253-4f14-8053-27876f553bd0.png)
![Save Website as Image-2022-08-24_09-38-14 Style Variation “Gray” – Stil Variation TT3](https://user-images.githubusercontent.com/85250773/186100767-7f1716d6-b7a3-4456-9233-d19056be27ed.png)
![Save Website as Image-2022-08-24_09-39-24 Style Variation “Gray” – Stil Variation TT3](https://user-images.githubusercontent.com/85250773/186100820-c1945f66-87cb-405b-82aa-21cd659e447d.png)

**Comment by elbsegler63** [comment]
The theme.json. Updated 2022-08-29:
[gray.zip](https://github.com/WordPress/twentytwentythree/files/9446866/gray.zip)

**Comment by beafialho** [comment]
Thanks for taking the time and effort to create a style variation! Since we had planned on accepting only a few submissions for final release, we will be closing out submissions that were not selected in order to keep this GitHub project focused for contributors.
